// 이 파일은 경쟁 앱 대비 첫 체감 품질을 높이기 위한 한국 집밥 큐레이션 레시피를 제공합니다.
import { EASY_RECIPE_EXPANSION } from "./easy-recipe-expansion.ts";
import type { RecipeDetailRecord, RecipeIngredientDetail, RecipeRecord } from "@/types";

export type CuratedRecipe = RecipeDetailRecord & {
  trustLabel: string;
  featuredReason: string;
};

const BABY_FOOD_SOURCE = {
  sourceProvider: "집밥노트",
  sourceExternalId: "baby-food-guidance-2026-05",
  sourceUrl: "https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=5212",
  sourceAttribution: "질병관리청 영유아 식이영양, WHO/CDC 보충식 기준, 어린이급식관리지원센터 식단표 참고",
  sourceLicense: "공개 보건정보 참고, 집밥노트 직접 작성 콘텐츠",
  contentOrigin: "original" as const,
  reviewedForBeginner: true,
};

const DEFAULT_MEASUREMENT_TIPS = [
  "1큰술 = 밥숟가락 평평하게 1번 = 약 15ml",
  "1작은술 = 티스푼 평평하게 1번 = 약 5ml",
  "1컵 = 일반 종이컵 1컵 = 약 180ml",
  "한줌 = 한 손으로 가볍게 집히는 양 = 약 30~50g",
];

const BABY_FOOD_MEASUREMENT_TIPS = [
  "1큰술 = 밥숟가락 평평하게 1번 = 약 15ml",
  "불린 쌀 20g = 밥숟가락 수북하게 약 2큰술",
  "초기 미음은 쌀 1:물 10, 중기 죽은 쌀 1:물 7 정도로 묽게 시작하세요.",
  "소금, 설탕, 꿀은 넣지 않고 아기 상태에 맞춰 농도만 조절하세요.",
];

function ingredient(
  name: string,
  display: string,
  beginnerNote?: string,
  prepNote?: string,
): RecipeIngredientDetail {
  return {
    name,
    display,
    beginnerNote: beginnerNote ?? null,
    prepNote: prepNote ?? null,
  };
}

const BASE_CURATED_JIPBAB_RECIPES: CuratedRecipe[] = [
  {
    id: "curated-kimchi-fried-rice",
    name: "김치볶음밥",
    category: "밥",
    method: "볶기",
    calories: "520",
    thumbnailUrl: "/images/recipes/kimchi-fried-rice.png",
    ingredients: "김치, 밥, 계란, 대파, 참기름",
    hashTag: "#한그릇 #냉장고파먹기 #초보가능",
    ingredientList: ["김치", "밥", "계란", "대파", "참기름"],
    ingredientDetails: [
      ingredient("김치", "1컵", "종이컵에 잘게 썬 김치를 가볍게 담은 양이에요.", "가위로 잘라도 괜찮아요."),
      ingredient("밥", "1공기", "햇반 1개 또는 밥공기 수북하지 않게 1그릇이에요.", "찬밥이면 더 잘 볶아져요."),
      ingredient("계란", "1개", "프라이로 올리면 실패해도 맛이 안정돼요."),
      ingredient("대파", "1/3대", "송송 썰어 밥숟가락 3큰술 정도면 충분해요."),
      ingredient("참기름", "1작은술", "티스푼 1번, 향만 내는 양이에요."),
    ],
    trustLabel: "집밥 기본",
    featuredReason: "김치와 계란만 있어도 바로 만들 수 있는 국민 한 그릇",
    difficulty: 1,
    cookingTime: 12,
    servings: 1,
    beginnerSummary: "김치가 짜면 간장을 빼고, 밥은 마지막에 넣어 눌어붙지 않게 풀어가며 볶으면 됩니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "계란프라이가 올라간 김치볶음밥 완성 사진",
    imageCaption: "김치는 충분히 볶고 밥은 마지막에 넣어야 질척하지 않아요.",
    steps: [
      {
        index: 1,
        description: "김치는 가위로 1cm 크기 정도로 잘게 자르고 대파는 송송 썹니다.",
        imageUrl: null,
        beginnerTip: "칼이 무서우면 김치를 그릇에 담고 주방가위로 잘라도 됩니다.",
        visualCue: "김치 조각이 숟가락에 올라가기 좋은 크기면 충분해요.",
      },
      {
        index: 2,
        description: "팬에 식용유 1큰술을 두르고 대파를 중불에서 30초 볶아 향을 냅니다.",
        imageUrl: null,
        beginnerTip: "식용유 1큰술은 밥숟가락으로 평평하게 1번입니다.",
        visualCue: "대파 향이 올라오고 가장자리가 살짝 투명해지면 다음 단계예요.",
      },
      {
        index: 3,
        description: "김치를 넣고 2분 정도 볶은 뒤 밥 1공기를 넣어 주걱으로 눌러 풀어줍니다.",
        imageUrl: null,
        beginnerTip: "밥덩어리가 있으면 불을 잠깐 약하게 줄이고 천천히 풀어도 됩니다.",
        visualCue: "밥알이 붉은 김치 양념색으로 고르게 물들면 됩니다.",
      },
      {
        index: 4,
        description: "불을 끄고 참기름 1작은술을 섞은 뒤 계란프라이를 올립니다.",
        imageUrl: null,
        beginnerTip: "참기름은 오래 가열하면 향이 날아가니 마지막에 넣어요.",
        visualCue: "밥에서 고소한 향이 나고 윤기가 살짝 돌면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-doenjang-jjigae",
    name: "된장찌개",
    category: "국·찌개",
    method: "끓이기",
    calories: "290",
    thumbnailUrl: "/images/recipes/jipbab-curated/doenjang-jjigae-basic.png",
    ingredients: "된장, 두부, 애호박, 양파, 대파",
    hashTag: "#국물 #집밥 #초보찌개",
    ingredientList: ["된장", "두부", "애호박", "양파", "대파"],
    ingredientDetails: [
      ingredient("된장", "2큰술", "밥숟가락 평평하게 2번, 약 30ml예요."),
      ingredient("두부", "1/2모", "마트 두부 한 모를 반으로 자른 양이에요.", "2cm 큐브로 썰면 잘 부서지지 않아요."),
      ingredient("애호박", "1/3개", "손가락 두 마디 길이 정도를 반달 모양으로 썰어요."),
      ingredient("양파", "1/4개", "작은 양파는 반 개까지 넣어도 괜찮아요."),
      ingredient("대파", "1/2대", "마지막 향을 내는 재료라 얇게 어슷썰면 좋아요."),
    ],
    trustLabel: "집밥 기본",
    featuredReason: "두부와 양파를 소진하기 좋은 가장 익숙한 찌개",
    difficulty: 1,
    cookingTime: 20,
    servings: 2,
    beginnerSummary: "된장은 처음부터 많이 넣지 말고 2큰술로 시작한 뒤 마지막에 맛을 보고 추가하세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "두부와 애호박이 보이는 된장찌개 완성 사진",
    imageCaption: "두부는 마지막 쪽에 넣어야 모양이 덜 부서집니다.",
    steps: [
      {
        index: 1,
        description: "냄비에 물 500ml를 붓고 된장 2큰술을 체나 숟가락으로 풀어줍니다.",
        imageUrl: null,
        beginnerTip: "500ml는 종이컵 약 2컵 반입니다.",
        visualCue: "된장 덩어리가 거의 안 보이면 충분히 풀린 상태예요.",
      },
      {
        index: 2,
        description: "애호박과 양파를 넣고 중불에서 5분 끓입니다.",
        imageUrl: null,
        beginnerTip: "끓기 시작하면 불을 중불로 낮춰 넘치지 않게 합니다.",
        visualCue: "애호박 가장자리가 반투명해지면 익기 시작한 거예요.",
      },
      {
        index: 3,
        description: "두부와 대파를 넣고 3분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "두부를 넣은 뒤에는 세게 젓지 말고 숟가락으로 살살 밀어주세요.",
        visualCue: "두부가 따뜻해지고 국물이 다시 보글보글 끓으면 됩니다.",
      },
      {
        index: 4,
        description: "간을 보고 싱거우면 된장 1작은술을 더 풀어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "짜면 물 100ml를 추가하고 1분 더 끓이면 됩니다.",
        visualCue: "국물이 짜지 않고 구수하면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-gyeran-mari",
    name: "계란말이",
    category: "반찬",
    method: "부치기",
    calories: "260",
    thumbnailUrl: "/images/recipes/jipbab-curated/gyeran-mari-basic.png",
    ingredients: "계란, 대파, 당근, 소금, 식용유",
    hashTag: "#반찬 #도시락 #초보팬요리",
    ingredientList: ["계란", "대파", "당근", "소금", "식용유"],
    ingredientDetails: [
      ingredient("계란", "4개", "2인 반찬 기준입니다. 처음이면 3개보다 4개가 말기 쉬워요."),
      ingredient("대파", "2큰술", "잘게 썬 대파를 밥숟가락으로 2번 떠 넣는 양이에요."),
      ingredient("당근", "2큰술", "색을 내는 정도라 없으면 생략해도 됩니다."),
      ingredient("소금", "1/4작은술", "티스푼 끝에 얇게 깔리는 정도예요."),
      ingredient("식용유", "1큰술", "팬을 코팅할 만큼만 얇게 둘러요."),
    ],
    trustLabel: "집밥 기본",
    featuredReason: "계란 소진과 반찬 준비를 동시에 해결",
    difficulty: 1,
    cookingTime: 15,
    servings: 2,
    beginnerSummary: "계란말이는 센불보다 약불이 중요합니다. 찢어져도 다음 계란물로 감싸면 모양이 살아납니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "대파와 당근이 들어간 계란말이 완성 사진",
    imageCaption: "약불에서 천천히 말면 겉은 타지 않고 속까지 익습니다.",
    steps: [
      {
        index: 1,
        description: "계란 4개를 그릇에 깨고 소금 1/4작은술, 다진 대파와 당근을 섞습니다.",
        imageUrl: null,
        beginnerTip: "젓가락으로 흰자 덩어리가 안 보일 때까지 풀면 표면이 매끈해져요.",
        visualCue: "계란물 색이 균일하고 채소가 골고루 보이면 됩니다.",
      },
      {
        index: 2,
        description: "약불 팬에 식용유 1큰술을 두르고 키친타월로 얇게 펴 바릅니다.",
        imageUrl: null,
        beginnerTip: "기름이 너무 많으면 계란이 미끄러져 말기 어려워요.",
        visualCue: "팬 표면이 살짝 반짝이는 정도면 충분합니다.",
      },
      {
        index: 3,
        description: "계란물을 얇게 붓고 윗면이 70% 정도 익으면 끝에서부터 접듯이 말아줍니다.",
        imageUrl: null,
        beginnerTip: "젖은 부분이 조금 남아 있어야 다음 층과 잘 붙습니다.",
        visualCue: "윗면이 흐르지 않지만 촉촉해 보이는 순간이 말기 좋아요.",
      },
      {
        index: 4,
        description: "남은 계란물을 2~3번 나눠 붓고 같은 방식으로 말아 두껍게 만듭니다.",
        imageUrl: null,
        beginnerTip: "찢어지면 당황하지 말고 다음 계란물로 덮어서 말면 됩니다.",
        visualCue: "전체가 네모난 막대 모양이 되면 불을 끕니다.",
      },
      {
        index: 5,
        description: "2분 식힌 뒤 1.5cm 두께로 썰어 접시에 담습니다.",
        imageUrl: null,
        beginnerTip: "뜨거울 때 바로 썰면 부서지기 쉬워요.",
        visualCue: "칼에 계란이 많이 묻지 않으면 썰기 좋은 온도입니다.",
      },
    ],
  },
  {
    id: "curated-dubu-jorim",
    name: "두부조림",
    category: "반찬",
    method: "조리기",
    calories: "310",
    thumbnailUrl: "/images/recipes/jipbab-curated/dubu-jorim-basic.png",
    ingredients: "두부, 간장, 대파, 고춧가루, 마늘",
    hashTag: "#두부 #밑반찬 #양념장",
    ingredientList: ["두부", "간장", "대파", "고춧가루", "마늘"],
    ingredientDetails: [
      ingredient("두부", "1모", "일반 부침용 두부 300g 한 팩 기준이에요.", "키친타월로 물기를 닦으면 덜 튀어요."),
      ingredient("간장", "2큰술", "밥숟가락 평평하게 2번, 약 30ml예요."),
      ingredient("고춧가루", "1큰술", "매운맛이 걱정되면 1/2큰술부터 시작하세요."),
      ingredient("마늘", "1작은술", "다진 마늘을 티스푼으로 1번 넣는 양입니다."),
      ingredient("대파", "1/2대", "양념에 섞을 만큼 송송 썰어요."),
    ],
    trustLabel: "집밥 기본",
    featuredReason: "유통기한 짧은 두부를 가장 빨리 처리하는 반찬",
    difficulty: 1,
    cookingTime: 18,
    servings: 2,
    beginnerSummary: "두부는 먼저 구워야 잘 부서지지 않고, 양념장은 물을 조금 섞어야 타지 않습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "간장 고춧가루 양념이 배어 있는 두부조림 완성 사진",
    imageCaption: "양념을 넣은 뒤에는 센불보다 중약불에서 천천히 졸입니다.",
    steps: [
      {
        index: 1,
        description: "두부 1모를 1.5cm 두께로 썰고 키친타월로 앞뒤 물기를 닦습니다.",
        imageUrl: null,
        beginnerTip: "두부 물기가 많으면 기름이 튈 수 있어요.",
        visualCue: "두부 표면이 번들거리지 않고 보송하면 됩니다.",
      },
      {
        index: 2,
        description: "간장 2큰술, 고춧가루 1큰술, 마늘 1작은술, 물 4큰술, 대파를 섞습니다.",
        imageUrl: null,
        beginnerTip: "물 4큰술은 밥숟가락으로 4번, 약 60ml입니다.",
        visualCue: "양념이 되직한 고추장보다 묽게 흐르면 좋아요.",
      },
      {
        index: 3,
        description: "팬에 식용유 1큰술을 두르고 두부를 앞뒤로 2분씩 굽습니다.",
        imageUrl: null,
        beginnerTip: "자주 뒤집으면 부서지니 한 면이 익을 때까지 기다립니다.",
        visualCue: "두부 가장자리가 연한 갈색이 되면 뒤집습니다.",
      },
      {
        index: 4,
        description: "양념장을 두부 위에 붓고 중약불에서 4분 정도 자작하게 조립니다.",
        imageUrl: null,
        beginnerTip: "국물이 너무 빨리 줄면 물 2큰술을 추가하세요.",
        visualCue: "양념이 두부 사이에 남아 있고 팬 바닥이 마르지 않으면 됩니다.",
      },
    ],
  },
  {
    id: "curated-pork-kimchi-jjigae",
    name: "돼지고기 김치찌개",
    category: "국·찌개",
    method: "끓이기",
    calories: "430",
    thumbnailUrl: "/images/recipes/jipbab-curated/pork-kimchi-jjigae-basic.png",
    ingredients: "김치, 돼지고기, 두부, 대파, 고춧가루",
    hashTag: "#김치찌개 #저녁메뉴 #국물",
    ingredientList: ["김치", "돼지고기", "두부", "대파", "고춧가루"],
    ingredientDetails: [
      ingredient("김치", "2컵", "종이컵 2컵, 대략 밥공기 1그릇 정도예요.", "신김치가 더 맛있어요."),
      ingredient("돼지고기", "200g", "한 줌 크게 두 번 집는 양, 삼겹살이나 앞다리살 모두 가능해요."),
      ingredient("두부", "1/2모", "두부 한 팩을 반으로 자른 양이에요."),
      ingredient("대파", "1/2대", "마지막에 넣으면 향이 살아납니다."),
      ingredient("고춧가루", "1큰술", "덜 맵게 먹으려면 1/2큰술만 넣으세요."),
    ],
    trustLabel: "저녁 추천",
    featuredReason: "김치와 두부가 있을 때 만족도가 높은 메인 메뉴",
    difficulty: 1,
    cookingTime: 28,
    servings: 2,
    beginnerSummary: "김치와 고기를 먼저 볶으면 깊은 맛이 나고, 물은 종이컵 3컵부터 시작하면 실패가 적습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "돼지고기와 두부가 들어간 김치찌개 완성 사진",
    imageCaption: "김치가 충분히 익어 국물이 붉고 진해지면 맛이 안정됩니다.",
    steps: [
      {
        index: 1,
        description: "김치는 한입 크기로 자르고 돼지고기는 3cm 크기로 준비합니다.",
        imageUrl: null,
        beginnerTip: "김치 국물 3큰술을 같이 넣으면 간과 색이 좋아집니다.",
        visualCue: "고기와 김치가 숟가락에 함께 올라가는 크기면 됩니다.",
      },
      {
        index: 2,
        description: "냄비에 돼지고기와 김치를 넣고 중불에서 3분 볶습니다.",
        imageUrl: null,
        beginnerTip: "기름이 없는 고기라면 식용유 1작은술을 먼저 두르세요.",
        visualCue: "고기 겉면이 하얗게 변하고 김치 향이 올라오면 됩니다.",
      },
      {
        index: 3,
        description: "물 600ml와 고춧가루 1큰술을 넣고 끓어오르면 중불로 낮춰 15분 끓입니다.",
        imageUrl: null,
        beginnerTip: "600ml는 종이컵 약 3컵입니다.",
        visualCue: "국물이 붉고 김치가 부드럽게 휘어지면 충분히 끓은 상태예요.",
      },
      {
        index: 4,
        description: "두부와 대파를 넣고 5분 더 끓인 뒤 간을 봅니다.",
        imageUrl: null,
        beginnerTip: "싱거우면 국간장 1작은술, 짜면 물 100ml를 추가하세요.",
        visualCue: "두부가 뜨겁게 데워지고 대파 향이 나면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-gamja-jorim",
    name: "감자조림",
    category: "반찬",
    method: "조리기",
    calories: "250",
    thumbnailUrl: "/images/recipes/jipbab-curated/gamja-jorim-basic.png",
    ingredients: "감자, 간장, 설탕, 식용유, 참기름",
    hashTag: "#감자 #밑반찬 #도시락",
    ingredientList: ["감자", "간장", "설탕", "식용유", "참기름"],
    ingredientDetails: [
      ingredient("감자", "2개", "중간 크기 감자 2개, 한입 크기로 썰면 익히기 쉬워요."),
      ingredient("간장", "2큰술", "밥숟가락 2번, 약 30ml입니다."),
      ingredient("설탕", "1큰술", "단맛이 부담되면 1/2큰술만 넣어도 됩니다."),
      ingredient("식용유", "1큰술", "감자 겉면을 코팅하는 양입니다."),
      ingredient("참기름", "1작은술", "마지막 향내기용이라 불 끈 뒤 넣어요."),
    ],
    trustLabel: "밑반찬",
    featuredReason: "상온 재료와 기본 양념만으로 만들기 쉬운 반찬",
    difficulty: 1,
    cookingTime: 22,
    servings: 2,
    beginnerSummary: "감자는 2cm 정도로 작게 썰어야 속까지 빨리 익고, 국물이 바닥에 2~3큰술 남을 때 멈추면 됩니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "윤기 있게 졸인 감자조림 완성 사진",
    imageCaption: "국물이 완전히 마르기 전에 불을 꺼야 촉촉하게 남습니다.",
    steps: [
      {
        index: 1,
        description: "감자는 2cm 크기로 썰어 찬물에 5분 담갔다가 물기를 뺍니다.",
        imageUrl: null,
        beginnerTip: "전분을 빼면 팬에 덜 들러붙습니다.",
        visualCue: "감자 표면의 뿌연 물이 빠지면 됩니다.",
      },
      {
        index: 2,
        description: "팬에 식용유 1큰술을 두르고 감자를 중불에서 2분 볶습니다.",
        imageUrl: null,
        beginnerTip: "감자가 팬에 붙으면 불을 조금 낮추세요.",
        visualCue: "감자 겉면이 살짝 투명해지면 됩니다.",
      },
      {
        index: 3,
        description: "간장 2큰술, 설탕 1큰술, 물 150ml를 넣고 뚜껑을 덮어 10분 익힙니다.",
        imageUrl: null,
        beginnerTip: "150ml는 종이컵 4/5컵 정도입니다.",
        visualCue: "젓가락이 감자에 부드럽게 들어가면 익은 거예요.",
      },
      {
        index: 4,
        description: "뚜껑을 열고 국물이 2~3큰술 남을 때까지 저어가며 졸인 뒤 참기름을 넣습니다.",
        imageUrl: null,
        beginnerTip: "국물이 완전히 없어질 때까지 졸이면 탈 수 있어요.",
        visualCue: "감자 표면에 윤기가 돌고 팬 바닥에 양념이 조금 남으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-soy-garlic-chicken",
    name: "간장마늘 닭조림",
    category: "일품",
    method: "조리기",
    calories: "610",
    thumbnailUrl: "/images/recipes/soy-garlic-chicken.png",
    ingredients: "닭고기, 간장, 마늘, 양파, 대파",
    hashTag: "#닭고기 #메인반찬 #간장양념",
    ingredientList: ["닭고기", "간장", "마늘", "양파", "대파"],
    ingredientDetails: [
      ingredient("닭고기", "400g", "닭다리살이나 닭가슴살 2인분 정도예요.", "키친타월로 물기를 닦으면 잡내가 줄어요."),
      ingredient("간장", "3큰술", "밥숟가락 3번, 약 45ml입니다."),
      ingredient("마늘", "1큰술", "다진 마늘 밥숟가락 1번입니다."),
      ingredient("양파", "1/2개", "채 썰어 넣으면 단맛이 나요."),
      ingredient("대파", "1/2대", "마지막에 넣어 향을 살립니다."),
    ],
    trustLabel: "저녁 추천",
    featuredReason: "냉장고 채소를 곁들여 메인 요리로 만들기 좋음",
    difficulty: 2,
    cookingTime: 30,
    servings: 2,
    beginnerSummary: "닭은 먼저 겉면을 익힌 뒤 물을 넣고 졸이면 속까지 익고 양념이 잘 배어듭니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "감자와 당근이 들어간 간장마늘 닭조림 완성 사진",
    imageCaption: "양념이 걸쭉해지고 닭 속이 하얗게 익으면 완성입니다.",
    steps: [
      {
        index: 1,
        description: "닭고기는 한입 크기로 자르고 키친타월로 물기를 닦습니다.",
        imageUrl: null,
        beginnerTip: "물기가 많으면 굽는 대신 삶아지는 느낌이 날 수 있어요.",
        visualCue: "표면이 번들거리지 않고 보송하면 됩니다.",
      },
      {
        index: 2,
        description: "팬에 닭고기를 넣고 중불에서 겉면이 하얗게 될 때까지 4분 굽습니다.",
        imageUrl: null,
        beginnerTip: "처음에는 자주 뒤집지 말고 한 면씩 익히세요.",
        visualCue: "닭 겉면의 분홍색이 거의 사라지면 다음 단계입니다.",
      },
      {
        index: 3,
        description: "간장 3큰술, 마늘 1큰술, 물 200ml, 양파를 넣고 15분 조립니다.",
        imageUrl: null,
        beginnerTip: "200ml는 종이컵 1컵보다 조금 많은 양입니다.",
        visualCue: "양념이 반 정도 줄고 닭에 갈색 윤기가 돌면 좋아요.",
      },
      {
        index: 4,
        description: "대파를 넣고 2분 더 졸여 마무리합니다.",
        imageUrl: null,
        beginnerTip: "닭이 익었는지 걱정되면 가장 두꺼운 조각을 잘라 속이 하얀지 확인하세요.",
        visualCue: "속살이 분홍색 없이 하얗고 육즙이 맑으면 익은 상태입니다.",
      },
    ],
  },
  {
    id: "curated-tuna-kimchi-fried-rice",
    name: "참치김치볶음밥",
    category: "밥",
    method: "볶기",
    calories: "560",
    thumbnailUrl: "/images/recipes/jipbab-curated/tuna-kimchi-fried-rice.png",
    ingredients: "참치캔, 김치, 밥, 대파, 계란",
    hashTag: "#참치캔 #한그릇 #자취요리",
    ingredientList: ["참치캔", "김치", "밥", "대파", "계란"],
    ingredientDetails: [
      ingredient("참치캔", "1/2캔", "작은 캔 기준 반 캔입니다. 기름은 1큰술만 남기면 고소해요."),
      ingredient("김치", "1컵", "종이컵 1컵, 잘게 자른 양입니다."),
      ingredient("밥", "1공기", "찬밥이나 즉석밥 1개 기준입니다."),
      ingredient("대파", "1/3대", "송송 썰어 향을 냅니다."),
      ingredient("계란", "1개", "프라이로 올리면 한 끼 느낌이 좋아집니다."),
    ],
    trustLabel: "한그릇",
    featuredReason: "캔참치와 남은 김치로 빠르게 해결하는 메뉴",
    difficulty: 1,
    cookingTime: 12,
    servings: 1,
    beginnerSummary: "참치 기름을 조금 남겨 볶으면 식용유를 많이 쓰지 않아도 고소합니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "계란프라이가 올라간 참치김치볶음밥 완성 사진",
    imageCaption: "참치는 오래 볶지 말고 김치가 익은 뒤 넣어야 퍽퍽하지 않습니다.",
    steps: [
      {
        index: 1,
        description: "참치캔은 기름 1큰술만 남기고 김치는 1cm 크기로 자릅니다.",
        imageUrl: null,
        beginnerTip: "참치 기름을 전부 버리지 않으면 볶을 때 고소한 맛이 납니다.",
        visualCue: "캔 바닥에 기름이 살짝 남은 정도면 됩니다.",
      },
      {
        index: 2,
        description: "팬에 대파를 30초 볶고 김치를 넣어 2분 더 볶습니다.",
        imageUrl: null,
        beginnerTip: "김치가 너무 시면 설탕 1작은술을 넣어도 됩니다.",
        visualCue: "김치 색이 진해지고 신 냄새가 줄면 됩니다.",
      },
      {
        index: 3,
        description: "참치와 밥을 넣고 밥알을 풀어가며 2분 볶습니다.",
        imageUrl: null,
        beginnerTip: "밥이 뭉치면 주걱을 세워 자르듯이 풀어주세요.",
        visualCue: "밥알에 김치색이 골고루 묻으면 됩니다.",
      },
      {
        index: 4,
        description: "불을 끄고 참기름 1작은술을 섞은 뒤 계란프라이를 올립니다.",
        imageUrl: null,
        beginnerTip: "계란은 반숙이 어려우면 완숙으로 익혀도 괜찮아요.",
        visualCue: "밥이 고슬고슬하고 기름지게 뭉치지 않으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-soy-egg-rice",
    name: "간장계란밥",
    category: "밥",
    method: "비비기",
    calories: "460",
    thumbnailUrl: "/images/recipes/jipbab-curated/soy-egg-rice.png",
    ingredients: "계란, 밥, 간장, 참기름, 김",
    hashTag: "#5분요리 #계란 #자취밥",
    ingredientList: ["계란", "밥", "간장", "참기름", "김"],
    ingredientDetails: [
      ingredient("밥", "1공기", "즉석밥 1개 또는 밥공기 1그릇이에요."),
      ingredient("계란", "1개", "처음이면 완숙 프라이가 가장 쉽습니다."),
      ingredient("간장", "1큰술", "밥숟가락 평평하게 1번, 약 15ml입니다."),
      ingredient("참기름", "1작은술", "티스푼 1번, 약 5ml만 넣어도 향이 충분해요."),
      ingredient("김", "1장", "조미김 1봉을 부숴 넣어도 됩니다."),
    ],
    trustLabel: "5분 한끼",
    featuredReason: "계란 하나로 바로 해결하는 가장 쉬운 집밥",
    difficulty: 1,
    cookingTime: 5,
    servings: 1,
    beginnerSummary: "간장은 처음부터 많이 넣지 말고 1큰술만 넣은 뒤 비벼서 맛을 보고 추가하세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "계란을 올린 간장계란밥 완성 예시",
    imageCaption: "노른자를 터뜨려 밥과 먼저 섞으면 간장이 적어도 고소합니다.",
    steps: [
      {
        index: 1,
        description: "따뜻한 밥 1공기를 그릇에 담습니다.",
        imageUrl: null,
        beginnerTip: "찬밥이면 전자레인지에 1분 데우면 비비기 쉬워요.",
        visualCue: "밥알이 따뜻하고 뭉친 부분이 풀리면 됩니다.",
      },
      {
        index: 2,
        description: "팬에 식용유 1작은술을 두르고 계란 1개를 프라이합니다.",
        imageUrl: null,
        beginnerTip: "반숙이 어렵다면 노른자까지 완전히 익혀도 괜찮아요.",
        visualCue: "흰자가 투명하지 않고 하얗게 굳으면 먹을 수 있습니다.",
      },
      {
        index: 3,
        description: "밥 위에 계란, 간장 1큰술, 참기름 1작은술을 올립니다.",
        imageUrl: null,
        beginnerTip: "간장 1큰술은 밥숟가락으로 넘치지 않게 한 번입니다.",
        visualCue: "간장이 밥 위에 한 바퀴 얇게 도는 정도면 충분해요.",
      },
      {
        index: 4,
        description: "김을 잘게 부숴 넣고 숟가락으로 골고루 비빕니다.",
        imageUrl: null,
        beginnerTip: "싱거우면 간장 1작은술만 추가하세요.",
        visualCue: "밥알에 노른자와 간장이 고르게 묻으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-steamed-egg",
    name: "부드러운 계란찜",
    category: "반찬",
    method: "찌기",
    calories: "210",
    thumbnailUrl: "/images/recipes/jipbab-curated/steamed-egg.png",
    ingredients: "계란, 물, 대파, 소금, 참기름",
    hashTag: "#계란찜 #부드러운반찬 #초보가능",
    ingredientList: ["계란", "물", "대파", "소금", "참기름"],
    ingredientDetails: [
      ingredient("계란", "3개", "작은 뚝배기나 전자레인지용 그릇 1개 분량입니다."),
      ingredient("물", "150ml", "종이컵 4/5컵 정도예요."),
      ingredient("대파", "1큰술", "송송 썬 대파를 밥숟가락 1번 넣습니다."),
      ingredient("소금", "1/4작은술", "티스푼 끝에 얇게 깔리는 정도입니다."),
      ingredient("참기름", "1/2작은술", "마지막 향내기용이라 생략해도 됩니다."),
    ],
    trustLabel: "초보 반찬",
    featuredReason: "계란을 많이 보유했을 때 실패 적게 만드는 반찬",
    difficulty: 1,
    cookingTime: 12,
    servings: 2,
    beginnerSummary: "계란과 물 비율은 계란 3개에 물 150ml로 시작하면 너무 단단하지 않습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "부드러운 계란찜 완성 예시",
    imageCaption: "센불로 오래 끓이면 구멍이 커지니 약불로 천천히 익힙니다.",
    steps: [
      {
        index: 1,
        description: "그릇에 계란 3개, 물 150ml, 소금 1/4작은술을 넣고 잘 풉니다.",
        imageUrl: null,
        beginnerTip: "체에 거르면 더 부드럽지만, 처음에는 젓가락으로 충분히 풀어도 됩니다.",
        visualCue: "흰자 덩어리가 거의 보이지 않으면 좋아요.",
      },
      {
        index: 2,
        description: "작은 냄비나 뚝배기에 계란물을 붓고 중약불에 올립니다.",
        imageUrl: null,
        beginnerTip: "바닥이 눌어붙지 않게 처음 1분은 숟가락으로 천천히 저어주세요.",
        visualCue: "가장자리가 살짝 익기 시작하면 불을 약하게 줄입니다.",
      },
      {
        index: 3,
        description: "뚜껑을 덮고 약불에서 6분 익힌 뒤 대파를 올립니다.",
        imageUrl: null,
        beginnerTip: "전자레인지라면 랩을 살짝 덮고 2분 30초부터 확인하세요.",
        visualCue: "가운데가 출렁이지만 물처럼 흐르지 않으면 거의 익은 상태입니다.",
      },
      {
        index: 4,
        description: "불을 끄고 2분 뜸을 들인 뒤 참기름을 살짝 둘러 마무리합니다.",
        imageUrl: null,
        beginnerTip: "덜 익었으면 약불로 1분만 더 익히세요.",
        visualCue: "숟가락으로 떠도 물이 고이지 않으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-bean-sprout-soup",
    name: "콩나물국",
    category: "국·찌개",
    method: "끓이기",
    calories: "120",
    thumbnailUrl: "/images/recipes/jipbab-curated/bean-sprout-soup.png",
    ingredients: "콩나물, 대파, 마늘, 국간장, 소금",
    hashTag: "#국물 #콩나물 #해장",
    ingredientList: ["콩나물", "대파", "마늘", "국간장", "소금"],
    ingredientDetails: [
      ingredient("콩나물", "200g", "마트 콩나물 작은 봉지 1개 정도입니다.", "흐르는 물에 2번 헹궈요."),
      ingredient("대파", "1/2대", "송송 썰어 마지막에 넣습니다."),
      ingredient("마늘", "1작은술", "다진 마늘 티스푼 1번입니다."),
      ingredient("국간장", "1큰술", "밥숟가락 1번, 약 15ml입니다."),
      ingredient("소금", "1/4작은술", "마지막 간 조절용입니다."),
    ],
    trustLabel: "국물 기본",
    featuredReason: "콩나물 한 봉지를 가장 쉽게 소진하는 국",
    difficulty: 1,
    cookingTime: 15,
    servings: 2,
    beginnerSummary: "콩나물 비린내가 걱정되면 끓는 동안 뚜껑을 열고 끝까지 끓이는 방식으로 가세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "맑은 콩나물국 완성 예시",
    imageCaption: "맑은 국물은 간장을 적게 쓰고 소금으로 마무리하면 색이 탁해지지 않습니다.",
    steps: [
      {
        index: 1,
        description: "콩나물을 흐르는 물에 2번 헹구고 물기를 뺍니다.",
        imageUrl: null,
        beginnerTip: "상한 냄새가 나거나 물컹한 콩나물은 빼주세요.",
        visualCue: "콩나물 머리가 노랗고 줄기가 단단하면 신선합니다.",
      },
      {
        index: 2,
        description: "냄비에 물 700ml를 붓고 콩나물과 마늘 1작은술을 넣어 끓입니다.",
        imageUrl: null,
        beginnerTip: "700ml는 종이컵 약 4컵입니다.",
        visualCue: "물이 끓으며 콩나물이 위로 떠오르면 익기 시작한 거예요.",
      },
      {
        index: 3,
        description: "끓어오르면 중불로 낮추고 7분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "뚜껑을 열었다 닫았다 하면 비린내가 날 수 있으니 처음부터 열고 끓이세요.",
        visualCue: "콩나물 줄기가 반투명하고 부드러워지면 됩니다.",
      },
      {
        index: 4,
        description: "국간장 1큰술과 대파를 넣고, 싱거우면 소금을 조금 넣어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "소금은 한 번에 많이 넣지 말고 한 꼬집씩 넣어 맛을 보세요.",
        visualCue: "국물이 맑고 콩나물 비린 향이 줄면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-cucumber-muchim",
    name: "오이무침",
    category: "반찬",
    method: "무치기",
    calories: "90",
    thumbnailUrl: "/images/recipes/jipbab-curated/cucumber-muchim.png",
    ingredients: "오이, 고춧가루, 식초, 설탕, 마늘",
    hashTag: "#오이 #무침 #10분반찬",
    ingredientList: ["오이", "고춧가루", "식초", "설탕", "마늘"],
    ingredientDetails: [
      ingredient("오이", "1개", "일반 오이 1개 기준입니다.", "양끝을 살짝 잘라내고 씻어요."),
      ingredient("고춧가루", "1큰술", "맵게 먹기 싫으면 1/2큰술부터 넣습니다."),
      ingredient("식초", "1큰술", "밥숟가락 1번, 새콤한 맛을 냅니다."),
      ingredient("설탕", "1작은술", "티스푼 1번, 신맛을 부드럽게 합니다."),
      ingredient("마늘", "1/2작은술", "많이 넣으면 매울 수 있어 조금만 넣습니다."),
    ],
    trustLabel: "10분 반찬",
    featuredReason: "불 없이 바로 만드는 상큼한 냉장고 반찬",
    difficulty: 1,
    cookingTime: 8,
    servings: 2,
    beginnerSummary: "오이는 너무 얇게 썰면 금방 물러지니 0.5cm 두께를 기준으로 썰면 식감이 좋습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "매콤하게 무친 오이무침 완성 예시",
    imageCaption: "먹기 직전에 무치면 물이 덜 생기고 아삭합니다.",
    steps: [
      {
        index: 1,
        description: "오이를 0.5cm 두께로 어슷하게 썹니다.",
        imageUrl: null,
        beginnerTip: "칼이 어렵다면 반달 모양으로 잘라도 맛은 같습니다.",
        visualCue: "오이 조각이 너무 얇아 접히지 않으면 좋아요.",
      },
      {
        index: 2,
        description: "그릇에 고춧가루 1큰술, 식초 1큰술, 설탕 1작은술, 마늘 1/2작은술을 섞습니다.",
        imageUrl: null,
        beginnerTip: "양념이 뻑뻑하면 물 1작은술을 넣어 풀어주세요.",
        visualCue: "양념이 숟가락에 고르게 묻는 정도면 됩니다.",
      },
      {
        index: 3,
        description: "오이를 넣고 손이나 숟가락으로 가볍게 버무립니다.",
        imageUrl: null,
        beginnerTip: "세게 주무르면 오이가 물러지니 살살 섞어주세요.",
        visualCue: "오이 표면에 빨간 양념이 골고루 묻으면 됩니다.",
      },
      {
        index: 4,
        description: "맛을 보고 싱거우면 소금 한 꼬집을 넣어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "짠맛보다 새콤달콤한 맛이 먼저 나야 밥반찬으로 좋아요.",
        visualCue: "그릇 바닥에 물이 많이 생기기 전 바로 먹으면 가장 아삭합니다.",
      },
    ],
  },
  {
    id: "curated-jeyuk-bokkeum",
    name: "제육볶음",
    category: "일품",
    method: "볶기",
    calories: "650",
    thumbnailUrl: "/images/recipes/jipbab-curated/jeyuk-bokkeum.png",
    ingredients: "돼지고기, 양파, 대파, 고추장, 간장",
    hashTag: "#돼지고기 #매콤 #저녁메뉴",
    ingredientList: ["돼지고기", "양파", "대파", "고추장", "간장"],
    ingredientDetails: [
      ingredient("돼지고기", "300g", "앞다리살이나 목살 2인분 정도입니다.", "키친타월로 핏물을 닦으면 잡내가 줄어요."),
      ingredient("양파", "1/2개", "채 썰면 단맛이 잘 나옵니다."),
      ingredient("대파", "1/2대", "마지막에 넣어 향을 살립니다."),
      ingredient("고추장", "1큰술", "밥숟가락 평평하게 1번입니다."),
      ingredient("간장", "2큰술", "밥숟가락 2번, 약 30ml입니다."),
    ],
    trustLabel: "저녁 추천",
    featuredReason: "돼지고기와 양파만 있어도 식사 만족도가 높은 메뉴",
    difficulty: 2,
    cookingTime: 25,
    servings: 2,
    beginnerSummary: "양념은 고기와 먼저 섞어두고, 팬에서는 센불보다 중불로 볶아야 타지 않습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "매콤한 제육볶음 완성 예시",
    imageCaption: "양념이 고기에 붙고 양파가 투명해지면 거의 완성입니다.",
    steps: [
      {
        index: 1,
        description: "돼지고기 300g에 고추장 1큰술, 간장 2큰술, 설탕 1큰술, 마늘 1큰술을 섞습니다.",
        imageUrl: null,
        beginnerTip: "설탕과 마늘은 기본 양념입니다. 없으면 설탕만 넣어도 됩니다.",
        visualCue: "고기 겉면이 빨간 양념으로 고르게 덮이면 됩니다.",
      },
      {
        index: 2,
        description: "양파는 채 썰고 대파는 어슷하게 썹니다.",
        imageUrl: null,
        beginnerTip: "두께가 일정하지 않아도 익으면서 숨이 죽습니다.",
        visualCue: "양파가 손가락 반 마디 폭 정도면 볶기 좋습니다.",
      },
      {
        index: 3,
        description: "팬을 중불로 달군 뒤 양념한 고기를 6분 볶습니다.",
        imageUrl: null,
        beginnerTip: "양념이 탈 것 같으면 물 2큰술을 넣고 볶으세요.",
        visualCue: "고기의 분홍색이 사라지고 양념이 끓듯이 붙으면 됩니다.",
      },
      {
        index: 4,
        description: "양파와 대파를 넣고 4분 더 볶아 마무리합니다.",
        imageUrl: null,
        beginnerTip: "고기 한 조각을 잘라 속까지 하얗게 익었는지 확인하세요.",
        visualCue: "양파가 투명하고 팬 바닥에 양념이 살짝 남으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-seaweed-soup",
    name: "소고기 미역국",
    category: "국·찌개",
    method: "끓이기",
    calories: "310",
    thumbnailUrl: "/images/recipes/jipbab-curated/beef-seaweed-soup.png",
    ingredients: "미역, 소고기, 국간장, 마늘, 참기름",
    hashTag: "#미역국 #국물 #기본한식",
    ingredientList: ["미역", "소고기", "국간장", "마늘", "참기름"],
    ingredientDetails: [
      ingredient("마른 미역", "10g", "한 줌보다 적은 양도 불리면 4배 이상 늘어납니다.", "찬물에 10분 불려요."),
      ingredient("소고기", "100g", "국거리 한 줌 정도입니다."),
      ingredient("국간장", "1큰술", "밥숟가락 1번, 약 15ml입니다."),
      ingredient("마늘", "1작은술", "다진 마늘 티스푼 1번입니다."),
      ingredient("참기름", "1큰술", "미역과 고기를 볶을 때 사용합니다."),
    ],
    trustLabel: "기본 한식",
    featuredReason: "마른 미역과 소고기로 오래 끓이지 않아도 깊은 국물",
    difficulty: 1,
    cookingTime: 25,
    servings: 2,
    beginnerSummary: "미역은 생각보다 많이 불어나니 처음에는 10g만 사용하고, 국간장은 색과 향을 내는 정도로 시작하세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "소고기 미역국 완성 예시",
    imageCaption: "미역을 참기름에 먼저 볶으면 국물 향이 깊어집니다.",
    steps: [
      {
        index: 1,
        description: "마른 미역 10g을 찬물에 10분 불린 뒤 물기를 짜고 먹기 좋게 자릅니다.",
        imageUrl: null,
        beginnerTip: "불린 미역이 너무 길면 가위로 잘라도 됩니다.",
        visualCue: "미역이 부드럽고 진한 초록색으로 풀리면 됩니다.",
      },
      {
        index: 2,
        description: "냄비에 참기름 1큰술을 두르고 소고기와 미역을 중불에서 3분 볶습니다.",
        imageUrl: null,
        beginnerTip: "고기가 냄비에 붙으면 불을 조금 낮추세요.",
        visualCue: "고기 겉면이 갈색으로 변하고 미역 향이 올라오면 됩니다.",
      },
      {
        index: 3,
        description: "물 800ml, 국간장 1큰술, 마늘 1작은술을 넣고 15분 끓입니다.",
        imageUrl: null,
        beginnerTip: "800ml는 종이컵 약 4컵 반입니다.",
        visualCue: "국물이 맑은 갈색이고 미역이 부드러워지면 좋아요.",
      },
      {
        index: 4,
        description: "맛을 보고 싱거우면 소금을 한 꼬집씩 넣어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "국간장을 많이 넣으면 색이 진해지니 마지막 간은 소금이 안전합니다.",
        visualCue: "국물이 짜지 않고 고소하면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-curry-rice",
    name: "카레라이스",
    category: "밥",
    method: "끓이기",
    calories: "620",
    thumbnailUrl: "/images/recipes/jipbab-curated/curry-rice.png",
    ingredients: "카레가루, 감자, 양파, 당근, 밥",
    hashTag: "#카레 #냉장고채소 #한그릇",
    ingredientList: ["카레가루", "감자", "양파", "당근", "밥"],
    ingredientDetails: [
      ingredient("카레가루", "4큰술", "고형 카레라면 2조각 정도입니다."),
      ingredient("감자", "1개", "작은 주사위 크기로 썰면 빨리 익어요."),
      ingredient("양파", "1/2개", "채소 단맛을 내는 기본 재료입니다."),
      ingredient("당근", "1/3개", "색을 내는 정도라 없으면 생략 가능합니다."),
      ingredient("밥", "2공기", "2인분 기준입니다."),
    ],
    trustLabel: "한그릇",
    featuredReason: "남은 채소를 한 번에 정리하기 좋은 메뉴",
    difficulty: 1,
    cookingTime: 25,
    servings: 2,
    beginnerSummary: "카레는 가루를 바로 넣으면 뭉칠 수 있어 불을 잠깐 끄고 풀어 넣는 게 안전합니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "감자와 양파가 들어간 카레라이스 완성 예시",
    imageCaption: "채소 크기를 작게 맞추면 초보자도 익힘 실패가 적습니다.",
    steps: [
      {
        index: 1,
        description: "감자, 양파, 당근을 1.5cm 크기로 썹니다.",
        imageUrl: null,
        beginnerTip: "크기가 조금 달라도 감자만 너무 크지 않으면 됩니다.",
        visualCue: "숟가락에 2~3조각 올라가는 크기면 먹기 좋아요.",
      },
      {
        index: 2,
        description: "냄비에 식용유 1큰술을 두르고 채소를 중불에서 3분 볶습니다.",
        imageUrl: null,
        beginnerTip: "양파가 먼저 투명해지면 단맛이 나기 시작합니다.",
        visualCue: "감자 가장자리가 살짝 투명해지면 물을 넣어도 됩니다.",
      },
      {
        index: 3,
        description: "물 500ml를 넣고 감자가 익을 때까지 10분 끓입니다.",
        imageUrl: null,
        beginnerTip: "500ml는 종이컵 약 2컵 반입니다.",
        visualCue: "젓가락이 감자에 부드럽게 들어가면 익은 상태입니다.",
      },
      {
        index: 4,
        description: "불을 약하게 줄이고 카레가루 4큰술을 풀어 3분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "가루가 뭉치면 국자로 눌러 풀어주세요.",
        visualCue: "국물이 걸쭉해지고 숟가락 뒷면에 묻으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-dumpling-soup",
    name: "떡만두국",
    category: "국·찌개",
    method: "끓이기",
    calories: "540",
    thumbnailUrl: "/images/recipes/jipbab-curated/tteok-mandu-guk.png",
    ingredients: "냉동만두, 떡, 계란, 대파, 국간장",
    hashTag: "#냉동만두 #떡국 #간단국물",
    ingredientList: ["냉동만두", "떡", "계란", "대파", "국간장"],
    ingredientDetails: [
      ingredient("냉동만두", "6개", "2인분 기준 중간 크기 만두 6개입니다."),
      ingredient("떡국떡", "1컵", "종이컵 1컵, 물에 한 번 헹궈요."),
      ingredient("계란", "1개", "마지막에 풀어 넣습니다."),
      ingredient("대파", "1/2대", "송송 썰어 국물 향을 냅니다."),
      ingredient("국간장", "1큰술", "밥숟가락 1번, 약 15ml입니다."),
    ],
    trustLabel: "냉동 활용",
    featuredReason: "냉동만두와 떡으로 빠르게 든든한 한 그릇",
    difficulty: 1,
    cookingTime: 15,
    servings: 2,
    beginnerSummary: "만두는 오래 끓이면 터질 수 있으니 떡을 먼저 넣고 만두는 중간에 넣는 순서가 좋습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "떡과 만두가 들어간 국 완성 예시",
    imageCaption: "만두피가 투명해지고 떡이 말랑하면 완성입니다.",
    steps: [
      {
        index: 1,
        description: "떡국떡 1컵을 물에 헹구고 대파를 송송 썹니다.",
        imageUrl: null,
        beginnerTip: "떡이 딱딱하면 찬물에 5분 담가두세요.",
        visualCue: "떡 표면의 하얀 가루가 씻겨 나가면 됩니다.",
      },
      {
        index: 2,
        description: "냄비에 물 700ml와 국간장 1큰술을 넣고 끓입니다.",
        imageUrl: null,
        beginnerTip: "육수팩이 있으면 같이 넣고 5분 뒤 빼면 더 맛있습니다.",
        visualCue: "물이 크게 끓어오르면 떡을 넣을 준비가 된 상태입니다.",
      },
      {
        index: 3,
        description: "떡을 넣고 3분 끓인 뒤 냉동만두 6개를 넣어 6분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "만두를 세게 저으면 터지니 국자로 살살 밀어주세요.",
        visualCue: "떡이 떠오르고 만두피가 살짝 투명해지면 익은 거예요.",
      },
      {
        index: 4,
        description: "계란 1개를 풀어 둘러 넣고 대파를 넣어 1분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "계란을 넣은 뒤 바로 세게 젓지 말고 10초 기다리세요.",
        visualCue: "계란이 노란 실처럼 익고 국물이 다시 끓으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-bibim-guksu",
    name: "비빔국수",
    category: "분식",
    method: "비비기",
    calories: "510",
    thumbnailUrl: "/images/recipes/jipbab-curated/bibim-guksu.png",
    ingredients: "국수, 고추장, 식초, 설탕, 참기름",
    hashTag: "#분식 #매콤새콤 #10분요리",
    ingredientList: ["국수", "고추장", "식초", "설탕", "참기름"],
    ingredientDetails: [
      ingredient("국수", "100g", "500원 동전 크기로 잡은 한 줌이 1인분 정도입니다."),
      ingredient("고추장", "1큰술", "밥숟가락 평평하게 1번입니다."),
      ingredient("식초", "1큰술", "새콤한 맛을 내는 기본 양입니다."),
      ingredient("설탕", "1큰술", "고추장 매운맛을 부드럽게 합니다."),
      ingredient("참기름", "1작은술", "마지막에 넣어 고소한 향을 냅니다."),
    ],
    trustLabel: "10분 한끼",
    featuredReason: "국수와 기본 양념만 있으면 바로 만드는 매콤한 한 끼",
    difficulty: 1,
    cookingTime: 12,
    servings: 1,
    beginnerSummary: "면은 삶은 뒤 찬물에 충분히 헹궈야 끈적이지 않고 양념이 깔끔하게 묻습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "매콤한 비빔국수 완성 예시",
    imageCaption: "면의 물기를 잘 빼야 양념이 묽어지지 않습니다.",
    steps: [
      {
        index: 1,
        description: "끓는 물에 국수 100g을 넣고 봉지 표기 시간보다 30초 짧게 삶습니다.",
        imageUrl: null,
        beginnerTip: "거품이 넘치면 찬물 1/2컵을 넣으면 가라앉습니다.",
        visualCue: "면 한 가닥을 먹었을 때 가운데 딱딱함이 없으면 됩니다.",
      },
      {
        index: 2,
        description: "삶은 면을 찬물에 2번 헹구고 체에 밭쳐 물기를 뺍니다.",
        imageUrl: null,
        beginnerTip: "손으로 가볍게 비벼 전분기를 씻어내세요.",
        visualCue: "면이 미끄럽지 않고 차갑게 식으면 좋습니다.",
      },
      {
        index: 3,
        description: "고추장 1큰술, 식초 1큰술, 설탕 1큰술, 참기름 1작은술을 섞습니다.",
        imageUrl: null,
        beginnerTip: "매운맛이 걱정되면 고추장을 1/2큰술로 줄이세요.",
        visualCue: "양념이 되직하지만 숟가락에서 천천히 떨어지면 됩니다.",
      },
      {
        index: 4,
        description: "면에 양념을 넣고 젓가락으로 들어 올리며 비빕니다.",
        imageUrl: null,
        beginnerTip: "양념은 2/3만 먼저 넣고 맛을 본 뒤 추가하면 안전합니다.",
        visualCue: "면 전체가 붉은색으로 고르게 물들면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-tuna-mayo-rice",
    name: "참치마요덮밥",
    category: "밥",
    method: "비비기",
    calories: "620",
    thumbnailUrl: "/images/recipes/jipbab-curated/tuna-mayo-rice-bowl.png",
    ingredients: "참치캔, 밥, 마요네즈, 간장, 김",
    hashTag: "#참치캔 #덮밥 #자취요리",
    ingredientList: ["참치캔", "밥", "마요네즈", "간장", "김"],
    ingredientDetails: [
      ingredient("참치캔", "1캔", "작은 캔 1개 기준입니다.", "기름은 대부분 빼고 사용합니다."),
      ingredient("밥", "1공기", "즉석밥 1개도 가능합니다."),
      ingredient("마요네즈", "1큰술", "밥숟가락 1번, 느끼하면 1/2큰술만 넣으세요."),
      ingredient("간장", "1작은술", "티스푼 1번, 짠맛을 살짝 보탭니다."),
      ingredient("김", "1장", "조미김 1봉을 부숴도 됩니다."),
    ],
    trustLabel: "캔 활용",
    featuredReason: "불 없이 캔참치로 만드는 실패 적은 덮밥",
    difficulty: 1,
    cookingTime: 7,
    servings: 1,
    beginnerSummary: "참치 기름을 너무 많이 남기면 느끼하니 숟가락으로 꾹 눌러 대부분 빼고 시작하세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "참치마요덮밥 완성 예시",
    imageCaption: "마요네즈는 처음부터 많이 넣지 말고 부족하면 추가합니다.",
    steps: [
      {
        index: 1,
        description: "참치캔 기름을 빼고 참치를 그릇에 담습니다.",
        imageUrl: null,
        beginnerTip: "캔 뚜껑으로 참치를 눌러 기름을 빼면 쉽습니다.",
        visualCue: "참치가 축축하지만 기름이 고이지 않으면 됩니다.",
      },
      {
        index: 2,
        description: "참치에 마요네즈 1큰술, 간장 1작은술을 넣고 섞습니다.",
        imageUrl: null,
        beginnerTip: "마요네즈가 많으면 느끼하니 처음엔 1큰술만 넣으세요.",
        visualCue: "참치가 촉촉하게 뭉치면 충분합니다.",
      },
      {
        index: 3,
        description: "따뜻한 밥 1공기 위에 참치마요를 올립니다.",
        imageUrl: null,
        beginnerTip: "밥이 너무 뜨거우면 마요네즈가 묽어지니 1분 식혀도 좋습니다.",
        visualCue: "참치가 밥 위에 고르게 덮이면 먹기 편합니다.",
      },
      {
        index: 4,
        description: "김을 잘게 부숴 올리고 기호에 따라 계란프라이를 곁들입니다.",
        imageUrl: null,
        beginnerTip: "싱거우면 간장 1작은술을 밥 가장자리로 추가하세요.",
        visualCue: "김이 눅눅해지기 전 바로 먹으면 가장 맛있습니다.",
      },
    ],
  },
  {
    id: "curated-cabbage-egg-stir-fry",
    name: "양배추계란볶음",
    category: "반찬",
    method: "볶기",
    calories: "260",
    thumbnailUrl: "/images/recipes/jipbab-curated/cabbage-egg-stirfry.png",
    ingredients: "양배추, 계란, 굴소스, 대파, 식용유",
    hashTag: "#양배추 #계란 #가벼운반찬",
    ingredientList: ["양배추", "계란", "굴소스", "대파", "식용유"],
    ingredientDetails: [
      ingredient("양배추", "2컵", "채 썬 양배추를 종이컵으로 2컵 담은 양입니다."),
      ingredient("계란", "2개", "양배추와 함께 볶으면 한 끼 반찬이 됩니다."),
      ingredient("굴소스", "1큰술", "밥숟가락 1번, 없으면 간장 1큰술로 대체하세요."),
      ingredient("대파", "1/3대", "기름에 먼저 볶아 향을 냅니다."),
      ingredient("식용유", "1큰술", "팬을 코팅하는 양입니다."),
    ],
    trustLabel: "냉장고 털기",
    featuredReason: "남은 양배추와 계란을 빠르게 처리하는 반찬",
    difficulty: 1,
    cookingTime: 12,
    servings: 2,
    beginnerSummary: "양배추는 오래 볶으면 물이 많이 생기니 숨이 살짝 죽는 정도에서 멈추세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "양배추와 계란을 함께 볶은 반찬 완성 예시",
    imageCaption: "양배추가 살짝 투명해질 때 계란을 넣으면 식감이 살아 있습니다.",
    steps: [
      {
        index: 1,
        description: "양배추는 얇게 채 썰고 대파는 송송 썹니다.",
        imageUrl: null,
        beginnerTip: "칼질이 어렵다면 양배추를 손으로 작게 찢어도 됩니다.",
        visualCue: "양배추 조각이 한입에 들어가는 크기면 됩니다.",
      },
      {
        index: 2,
        description: "계란 2개를 그릇에 풀어둡니다.",
        imageUrl: null,
        beginnerTip: "흰자 덩어리가 조금 남아도 볶음에는 괜찮습니다.",
        visualCue: "노른자와 흰자가 대략 섞이면 충분합니다.",
      },
      {
        index: 3,
        description: "팬에 식용유 1큰술과 대파를 넣고 30초 볶은 뒤 양배추를 넣어 3분 볶습니다.",
        imageUrl: null,
        beginnerTip: "양배추가 많아 보여도 익으면 금방 줄어듭니다.",
        visualCue: "양배추 가장자리가 투명해지면 계란을 넣을 때입니다.",
      },
      {
        index: 4,
        description: "계란과 굴소스 1큰술을 넣고 1분 더 볶아 마무리합니다.",
        imageUrl: null,
        beginnerTip: "계란이 너무 익기 전에 불을 끄면 촉촉합니다.",
        visualCue: "계란이 노랗게 굳고 양배추와 섞이면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-eomuk-bokkeum",
    name: "어묵볶음",
    category: "반찬",
    method: "볶기",
    calories: "290",
    thumbnailUrl: "/images/recipes/jipbab-curated/fishcake-bokkeum.png",
    ingredients: "어묵, 양파, 간장, 설탕, 대파",
    hashTag: "#어묵 #밑반찬 #도시락",
    ingredientList: ["어묵", "양파", "간장", "설탕", "대파"],
    ingredientDetails: [
      ingredient("어묵", "4장", "사각어묵 4장 기준입니다.", "뜨거운 물을 살짝 부으면 기름기가 줄어요."),
      ingredient("양파", "1/2개", "채 썰어 단맛을 냅니다."),
      ingredient("간장", "2큰술", "밥숟가락 2번, 약 30ml입니다."),
      ingredient("설탕", "1큰술", "단짠 양념의 단맛입니다."),
      ingredient("대파", "1/3대", "마지막 향내기용입니다."),
    ],
    trustLabel: "밑반찬",
    featuredReason: "냉장 어묵을 빠르게 처리하는 국민 반찬",
    difficulty: 1,
    cookingTime: 12,
    servings: 2,
    beginnerSummary: "어묵은 이미 익은 식품이라 오래 볶지 않아도 됩니다. 양념이 묻고 따뜻해지면 충분합니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "간장 양념 어묵볶음 완성 예시",
    imageCaption: "양념이 팬 바닥에 조금 남을 때 불을 꺼야 촉촉합니다.",
    steps: [
      {
        index: 1,
        description: "어묵은 한입 크기로 자르고 양파는 채 썹니다.",
        imageUrl: null,
        beginnerTip: "어묵은 가위로 잘라도 모양이 크게 상관없습니다.",
        visualCue: "어묵 조각이 숟가락에 올라가는 크기면 됩니다.",
      },
      {
        index: 2,
        description: "간장 2큰술, 설탕 1큰술, 물 3큰술을 섞어 양념장을 만듭니다.",
        imageUrl: null,
        beginnerTip: "물 3큰술을 넣어야 양념이 바로 타지 않습니다.",
        visualCue: "설탕 알갱이가 거의 녹으면 됩니다.",
      },
      {
        index: 3,
        description: "팬에 식용유 1작은술을 두르고 양파를 1분 볶습니다.",
        imageUrl: null,
        beginnerTip: "양파를 먼저 볶으면 단맛이 나와요.",
        visualCue: "양파 가장자리가 투명해지면 어묵을 넣습니다.",
      },
      {
        index: 4,
        description: "어묵과 양념장을 넣고 3분 볶은 뒤 대파를 넣어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "불이 세면 간장이 빨리 타니 중불을 유지하세요.",
        visualCue: "어묵 표면에 갈색 윤기가 돌면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-spinach-namul",
    name: "시금치나물",
    category: "반찬",
    method: "데치기",
    calories: "80",
    thumbnailUrl: "/images/recipes/jipbab-curated/spinach-namul.png",
    ingredients: "시금치, 소금, 참기름, 마늘, 깨",
    hashTag: "#나물 #초록반찬 #기본반찬",
    ingredientList: ["시금치", "소금", "참기름", "마늘", "깨"],
    ingredientDetails: [
      ingredient("시금치", "1단", "마트 시금치 한 묶음 기준입니다.", "뿌리 끝을 다듬고 흙을 씻어요."),
      ingredient("소금", "1/2작은술", "데칠 물과 무침 간에 나눠 씁니다."),
      ingredient("참기름", "1큰술", "고소한 향을 내는 핵심입니다."),
      ingredient("마늘", "1/2작은술", "많이 넣으면 매워질 수 있어 조금만 넣습니다."),
      ingredient("깨", "1작은술", "마지막에 뿌리면 고소합니다."),
    ],
    trustLabel: "기본 반찬",
    featuredReason: "시금치 한 단을 실패 없이 처리하는 기본 나물",
    difficulty: 1,
    cookingTime: 10,
    servings: 2,
    beginnerSummary: "시금치는 오래 데치면 물러지므로 끓는 물에 30초만 데치고 바로 찬물에 헹구세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "참기름에 무친 시금치나물 완성 예시",
    imageCaption: "물기를 꼭 짜야 양념이 싱거워지지 않습니다.",
    steps: [
      {
        index: 1,
        description: "시금치를 흐르는 물에 씻고 뿌리 끝을 다듬습니다.",
        imageUrl: null,
        beginnerTip: "흙이 남기 쉬우니 물을 갈아가며 2번 씻으세요.",
        visualCue: "잎 사이에 흙이 보이지 않으면 됩니다.",
      },
      {
        index: 2,
        description: "끓는 물에 소금 한 꼬집을 넣고 시금치를 30초 데칩니다.",
        imageUrl: null,
        beginnerTip: "시금치를 넣은 뒤 젓가락으로 한 번 뒤집어 주세요.",
        visualCue: "숨이 죽고 색이 진한 초록색이 되면 바로 꺼냅니다.",
      },
      {
        index: 3,
        description: "찬물에 헹군 뒤 두 손으로 물기를 꼭 짭니다.",
        imageUrl: null,
        beginnerTip: "물기가 많으면 양념이 흐려져 싱거워집니다.",
        visualCue: "손으로 눌렀을 때 물방울이 많이 떨어지지 않으면 됩니다.",
      },
      {
        index: 4,
        description: "참기름 1큰술, 마늘 1/2작은술, 소금 한 꼬집, 깨를 넣고 무칩니다.",
        imageUrl: null,
        beginnerTip: "소금은 한 번에 많이 넣지 말고 맛을 보며 추가하세요.",
        visualCue: "시금치에 윤기가 돌고 고소한 향이 나면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-kimchi-jeon",
    name: "김치전",
    category: "분식",
    method: "부치기",
    calories: "430",
    thumbnailUrl: "/images/recipes/jipbab-curated/kimchi-jeon.png",
    ingredients: "김치, 밀가루, 물, 대파, 식용유",
    hashTag: "#김치 #부침개 #비오는날",
    ingredientList: ["김치", "밀가루", "물", "대파", "식용유"],
    ingredientDetails: [
      ingredient("김치", "1컵", "잘게 썬 김치를 종이컵 1컵 담은 양입니다."),
      ingredient("밀가루", "1컵", "종이컵 1컵, 부침가루로 대체 가능합니다."),
      ingredient("물", "2/3컵", "종이컵 기준 2/3컵, 약 120ml입니다."),
      ingredient("대파", "2큰술", "송송 썬 대파를 밥숟가락 2번 넣습니다."),
      ingredient("식용유", "3큰술", "전을 바삭하게 부치려면 넉넉히 둘러요."),
    ],
    trustLabel: "김치 활용",
    featuredReason: "익은 김치를 간단한 간식이나 반찬으로 전환",
    difficulty: 2,
    cookingTime: 18,
    servings: 2,
    beginnerSummary: "반죽은 너무 되직하면 두껍고, 너무 묽으면 찢어집니다. 숟가락에서 천천히 흐르는 농도를 목표로 하세요.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "노릇하게 부친 김치전 완성 예시",
    imageCaption: "가장자리가 바삭하게 갈색이 되면 뒤집기 좋은 타이밍입니다.",
    steps: [
      {
        index: 1,
        description: "김치는 1cm 크기로 자르고 대파는 송송 썹니다.",
        imageUrl: null,
        beginnerTip: "김치 국물 2큰술을 넣으면 색과 맛이 좋아집니다.",
        visualCue: "김치가 반죽에 골고루 섞일 작은 크기면 됩니다.",
      },
      {
        index: 2,
        description: "그릇에 김치, 밀가루 1컵, 물 2/3컵, 대파를 넣고 섞습니다.",
        imageUrl: null,
        beginnerTip: "반죽이 너무 뻑뻑하면 물 1큰술씩 추가하세요.",
        visualCue: "숟가락으로 떴을 때 천천히 떨어지는 농도면 좋습니다.",
      },
      {
        index: 3,
        description: "팬에 식용유 2큰술을 두르고 반죽을 얇게 펴 중불에서 4분 부칩니다.",
        imageUrl: null,
        beginnerTip: "두껍게 부치면 속이 익기 전에 겉이 탈 수 있습니다.",
        visualCue: "가장자리가 마르고 갈색으로 변하면 뒤집을 때입니다.",
      },
      {
        index: 4,
        description: "뒤집어서 식용유 1큰술을 가장자리에 추가하고 3분 더 부칩니다.",
        imageUrl: null,
        beginnerTip: "뒤집기가 어렵다면 작은 크기로 여러 장 부쳐도 됩니다.",
        visualCue: "양면이 노릇하고 가운데가 질척하지 않으면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-tomato-egg-stir-fry",
    name: "토마토계란볶음",
    category: "일품",
    method: "볶기",
    calories: "300",
    thumbnailUrl: "/images/recipes/jipbab-curated/tomato-egg-stirfry.png",
    ingredients: "토마토, 계란, 대파, 소금, 식용유",
    hashTag: "#토마토 #계란 #가벼운한끼",
    ingredientList: ["토마토", "계란", "대파", "소금", "식용유"],
    ingredientDetails: [
      ingredient("토마토", "2개", "중간 크기 토마토 2개 또는 방울토마토 12개입니다."),
      ingredient("계란", "3개", "부드럽게 먹으려면 넉넉히 넣습니다."),
      ingredient("대파", "1/3대", "향을 내는 재료라 생략 가능해요."),
      ingredient("소금", "1/4작은술", "계란 간을 맞추는 양입니다."),
      ingredient("식용유", "1큰술", "계란을 먼저 익힐 때 씁니다."),
    ],
    trustLabel: "가벼운 한끼",
    featuredReason: "토마토와 계란만으로 만드는 부드러운 볶음",
    difficulty: 1,
    cookingTime: 12,
    servings: 2,
    beginnerSummary: "계란을 먼저 부드럽게 익혀 덜어낸 뒤 토마토와 다시 섞으면 질척하지 않습니다.",
    measurementTips: DEFAULT_MEASUREMENT_TIPS,
    imageAlt: "토마토와 계란을 볶은 완성 예시",
    imageCaption: "토마토가 살짝 무너지고 계란이 촉촉하면 완성입니다.",
    steps: [
      {
        index: 1,
        description: "토마토는 한입 크기로 자르고 계란 3개는 소금과 함께 풀어둡니다.",
        imageUrl: null,
        beginnerTip: "토마토 껍질이 신경 쓰이면 끓는 물에 10초 데쳐 벗겨도 됩니다.",
        visualCue: "토마토 조각이 숟가락에 올라가는 크기면 됩니다.",
      },
      {
        index: 2,
        description: "팬에 식용유 1큰술을 두르고 계란을 70% 정도 익혀 그릇에 덜어둡니다.",
        imageUrl: null,
        beginnerTip: "계란은 완전히 익히지 않아야 마지막에 촉촉합니다.",
        visualCue: "계란이 덩어리졌지만 표면이 살짝 촉촉하면 꺼내세요.",
      },
      {
        index: 3,
        description: "같은 팬에 대파와 토마토를 넣고 중불에서 3분 볶습니다.",
        imageUrl: null,
        beginnerTip: "토마토에서 물이 나오니 기름을 더 넣지 않아도 됩니다.",
        visualCue: "토마토 가장자리가 부드럽게 무너지면 됩니다.",
      },
      {
        index: 4,
        description: "계란을 다시 넣고 30초만 섞어 마무리합니다.",
        imageUrl: null,
        beginnerTip: "싱거우면 소금 한 꼬집을 추가하세요.",
        visualCue: "계란과 토마토가 섞였지만 계란이 촉촉하면 완성입니다.",
      },
    ],
  },
  {
    id: "curated-baby-rice-mium",
    name: "초기 쌀미음",
    category: "이유식",
    method: "끓이기",
    calories: "35",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-rice-mium.png",
    ingredients: "쌀",
    hashTag: "#초기이유식 #6개월 #쌀미음 #무간",
    ingredientList: ["쌀"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 20g", "처음 시작할 때는 쌀 한 가지로 아기 반응을 봅니다.", "30분 이상 불린 뒤 사용하세요."),
      ingredient("물", "200ml", "초기 미음은 쌀보다 물을 넉넉히 넣어 흐르는 농도로 만듭니다."),
      ingredient("끓인 물", "1큰술", "완성 후 너무 되직하면 한 숟가락씩 더해 농도를 맞춥니다."),
      ingredient("모유 또는 분유", "1큰술 선택", "아기가 낯설어하면 익숙한 향을 아주 소량 섞을 수 있습니다.", "가열 후 식힌 뒤 섞으세요."),
    ],
    trustLabel: "이유식 초기",
    featuredReason: "이유식 시작 전용, 한 가지 재료로 반응을 보는 기본 미음",
    difficulty: 1,
    cookingTime: 18,
    servings: 1,
    beginnerSummary: "생후 6개월 전후 준비 신호가 보일 때 쌀 한 가지로 시작하고, 소금·설탕·꿀은 넣지 않습니다. 알레르기나 성장 이슈가 있으면 소아과 상담을 우선하세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "작은 그릇에 담긴 묽은 쌀미음",
    imageCaption: "숟가락에서 주르륵 흐르는 정도로 묽게 시작합니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "쌀 20g을 씻어 30분 이상 불린 뒤 물기를 뺍니다.",
        imageUrl: null,
        beginnerTip: "첫 이유식은 새 재료를 한 번에 여러 개 섞지 않는 편이 안전합니다.",
        visualCue: "쌀알이 하얗게 불고 손으로 눌렀을 때 살짝 부서지면 됩니다.",
      },
      {
        index: 2,
        description: "냄비에 불린 쌀과 물 200ml를 넣고 약불에서 저어가며 끓입니다.",
        imageUrl: null,
        beginnerTip: "눌어붙기 쉬우니 바닥을 긁듯이 천천히 저어주세요.",
        visualCue: "쌀알이 퍼지고 물이 살짝 걸쭉해지면 다음 단계입니다.",
      },
      {
        index: 3,
        description: "믹서나 체로 곱게 갈아 덩어리가 남지 않게 만듭니다.",
        imageUrl: null,
        beginnerTip: "초기에는 덩어리가 거의 없는 질감이 삼키기 쉽습니다.",
        visualCue: "입자가 보이지 않고 숟가락에 얇게 묻으면 좋습니다.",
      },
      {
        index: 4,
        description: "미지근하게 식힌 뒤 1~2작은술부터 먹이며 반응을 확인합니다.",
        imageUrl: null,
        beginnerTip: "먹는 양보다 삼키는 연습과 반응 확인이 우선입니다.",
        visualCue: "김이 거의 나지 않고 손목 안쪽에 떨어뜨렸을 때 따뜻한 정도면 됩니다.",
      },
    ],
  },
  {
    id: "curated-baby-zucchini-mium",
    name: "초기 애호박미음",
    category: "이유식",
    method: "끓이기",
    calories: "42",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-zucchini-mium.png",
    ingredients: "쌀, 애호박",
    hashTag: "#초기이유식 #애호박 #채소미음 #무간",
    ingredientList: ["쌀", "애호박"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 20g", "쌀미음에 익숙해진 뒤 채소를 하나씩 더합니다."),
      ingredient("애호박", "15g", "껍질과 씨가 질기면 제거하고 속살 위주로 씁니다.", "작게 썰어 완전히 익혀 주세요."),
      ingredient("물", "220ml", "채소가 들어가도 초기에는 충분히 묽게 끓입니다."),
      ingredient("끓인 물", "1~2큰술", "체에 내린 뒤 되직하면 조금씩 더합니다."),
    ],
    trustLabel: "이유식 초기",
    featuredReason: "쌀미음 다음 단계로 넣기 쉬운 부드러운 채소 미음",
    difficulty: 1,
    cookingTime: 20,
    servings: 1,
    beginnerSummary: "쌀미음에 익숙해진 뒤 애호박 한 가지를 더해 반응을 확인합니다. 간은 하지 않고, 새 재료는 아기 상태를 보며 천천히 늘립니다.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "연한 초록빛 애호박미음",
    imageCaption: "애호박은 충분히 익혀 풋내와 섬유감을 줄입니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "애호박은 깨끗이 씻고 껍질과 씨를 정리한 뒤 잘게 썹니다.",
        imageUrl: null,
        beginnerTip: "처음 먹는 채소라면 양을 욕심내지 않고 10~15g만 넣습니다.",
        visualCue: "애호박 조각이 손톱보다 작으면 빨리 익습니다.",
      },
      {
        index: 2,
        description: "불린 쌀, 애호박, 물 220ml를 냄비에 넣고 약불에서 끓입니다.",
        imageUrl: null,
        beginnerTip: "센불은 금방 눌어붙으니 처음부터 약불이 안정적입니다.",
        visualCue: "애호박 색이 투명해지고 쌀이 퍼지면 충분히 익은 상태입니다.",
      },
      {
        index: 3,
        description: "완전히 익으면 곱게 갈고 체에 한 번 내려 껍질감을 줄입니다.",
        imageUrl: null,
        beginnerTip: "초기에는 체에 거르는 과정이 질감 실패를 줄여줍니다.",
        visualCue: "큰 초록 조각 없이 연한 색이 고르게 섞이면 됩니다.",
      },
      {
        index: 4,
        description: "소분해 식히고, 바로 먹을 양만 덜어 미지근하게 제공합니다.",
        imageUrl: null,
        beginnerTip: "남은 이유식은 빠르게 식혀 냉장 또는 냉동 보관하세요.",
        visualCue: "그릇을 기울였을 때 천천히 흐르면 먹이기 좋은 농도입니다.",
      },
    ],
  },
  {
    id: "curated-baby-beef-broccoli-porridge",
    name: "중기 소고기브로콜리죽",
    category: "이유식",
    method: "끓이기",
    calories: "82",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-beef-broccoli-porridge.png",
    ingredients: "쌀, 소고기, 브로콜리",
    hashTag: "#중기이유식 #소고기 #브로콜리 #철분",
    ingredientList: ["쌀", "소고기", "브로콜리"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 30g", "중기에는 초기보다 조금 되직한 7배죽 느낌으로 갑니다."),
      ingredient("소고기", "15g", "철분 보충을 위해 기름 적은 다짐육이나 안심을 사용합니다.", "핏물은 짧게 빼고 완전히 익히세요."),
      ingredient("브로콜리", "15g", "송이 윗부분 위주로 쓰면 질긴 줄기감을 줄일 수 있습니다.", "데쳐서 잘게 다집니다."),
      ingredient("물", "210ml", "쌀 1:물 7 정도를 기준으로 시작합니다."),
    ],
    trustLabel: "이유식 중기",
    featuredReason: "중기 이유식에서 자주 찾는 철분 보강형 소고기 채소죽",
    difficulty: 1,
    cookingTime: 25,
    servings: 1,
    beginnerSummary: "중기는 하루 2회 식사 리듬을 만들어가는 시기입니다. 소고기와 브로콜리는 완전히 익히고, 새 단백질 재료는 알레르기 반응을 확인하세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "소고기와 브로콜리가 섞인 중기 이유식 죽",
    imageCaption: "입자가 조금 보이되 혀로 으깰 수 있는 부드러움이 기준입니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "소고기는 잘게 다지고 브로콜리는 데친 뒤 송이 부분만 곱게 다집니다.",
        imageUrl: null,
        beginnerTip: "고기 덩어리가 크면 아기가 뱉을 수 있어 최대한 잘게 준비합니다.",
        visualCue: "소고기는 쌀알보다 작고 브로콜리는 초록 가루처럼 보이면 좋습니다.",
      },
      {
        index: 2,
        description: "냄비에 쌀과 물 210ml를 넣고 약불에서 먼저 10분 끓입니다.",
        imageUrl: null,
        beginnerTip: "쌀이 충분히 퍼진 뒤 단백질을 넣으면 질감이 안정됩니다.",
        visualCue: "쌀알이 부풀고 물이 탁해지면 다음 재료를 넣습니다.",
      },
      {
        index: 3,
        description: "소고기를 넣어 완전히 익힌 뒤 브로콜리를 넣고 3분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "고기가 분홍색이면 아직 덜 익은 상태입니다.",
        visualCue: "고기 색이 갈색으로 바뀌고 죽이 걸쭉해지면 됩니다.",
      },
      {
        index: 4,
        description: "아기 단계에 맞춰 가볍게 으깨거나 짧게 갈아 미지근하게 제공합니다.",
        imageUrl: null,
        beginnerTip: "중기 초반이면 조금 더 갈고, 익숙하면 입자를 남깁니다.",
        visualCue: "숟가락에서 뚝뚝 떨어지고 작은 입자가 보이면 중기 농도입니다.",
      },
    ],
  },
  {
    id: "curated-baby-chicken-zucchini-porridge",
    name: "중기 닭고기애호박죽",
    category: "이유식",
    method: "끓이기",
    calories: "76",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-chicken-zucchini-porridge.png",
    ingredients: "쌀, 닭고기, 애호박",
    hashTag: "#중기이유식 #닭고기 #애호박 #무간",
    ingredientList: ["쌀", "닭고기", "애호박"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 30g", "중기 죽 농도 기준입니다."),
      ingredient("닭고기", "15g", "닭가슴살이나 안심처럼 기름 적은 부위를 씁니다.", "껍질과 힘줄은 제거하세요."),
      ingredient("애호박", "20g", "부드러운 속살 위주로 잘게 다집니다."),
      ingredient("물", "210ml", "되직하면 끓인 물을 1큰술씩 추가합니다."),
    ],
    trustLabel: "이유식 중기",
    featuredReason: "담백한 단백질과 부드러운 채소를 섞은 중기 기본죽",
    difficulty: 1,
    cookingTime: 24,
    servings: 1,
    beginnerSummary: "닭고기는 껍질과 지방을 제거하고 완전히 익혀야 합니다. 향신료와 간은 넣지 않고 재료 본연의 맛으로 제공합니다.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "닭고기와 애호박이 섞인 중기 이유식 죽",
    imageCaption: "닭고기 입자를 잘게 풀어 퍽퍽함을 줄입니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "닭고기는 삶아서 속까지 익힌 뒤 결 반대 방향으로 곱게 다집니다.",
        imageUrl: null,
        beginnerTip: "삶은 물은 기름을 걷어내고 일부만 죽 농도 조절에 쓸 수 있습니다.",
        visualCue: "닭고기 속이 하얗고 분홍빛이 없으면 익은 상태입니다.",
      },
      {
        index: 2,
        description: "불린 쌀과 물을 냄비에 넣고 약불에서 쌀알이 퍼질 때까지 끓입니다.",
        imageUrl: null,
        beginnerTip: "뚜껑을 완전히 덮으면 넘칠 수 있어 살짝 열어둡니다.",
        visualCue: "죽 표면에 작은 기포가 올라오면 천천히 저어주세요.",
      },
      {
        index: 3,
        description: "다진 닭고기와 애호박을 넣고 5분 더 끓입니다.",
        imageUrl: null,
        beginnerTip: "애호박은 오래 끓이면 색이 탁해지니 후반에 넣습니다.",
        visualCue: "애호박이 반투명하고 닭고기가 죽에 고르게 섞이면 됩니다.",
      },
      {
        index: 4,
        description: "아기 씹는 단계에 맞춰 입자를 조절하고 한 김 식혀 제공합니다.",
        imageUrl: null,
        beginnerTip: "처음 닭고기를 먹는 날에는 다른 새 재료를 같이 늘리지 마세요.",
        visualCue: "작은 입자가 남아도 손가락으로 쉽게 으깨지면 좋습니다.",
      },
    ],
  },
  {
    id: "curated-baby-tofu-potato-soft-rice",
    name: "후기 두부감자진밥",
    category: "이유식",
    method: "끓이기",
    calories: "128",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-tofu-potato-soft-rice.png",
    ingredients: "쌀, 두부, 감자, 양파",
    hashTag: "#후기이유식 #두부 #감자 #진밥",
    ingredientList: ["쌀", "두부", "감자", "양파"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 40g", "후기는 5배죽이나 무른밥으로 넘어가는 단계입니다."),
      ingredient("두부", "25g", "대두 알레르기 반응을 확인한 뒤 사용하세요.", "끓는 물에 데쳐 으깨면 냄새가 줄어듭니다."),
      ingredient("감자", "25g", "푹 익히면 자연스럽게 농도를 잡아줍니다."),
      ingredient("양파", "10g", "충분히 익히면 단맛이 나서 간 없이도 먹기 쉽습니다."),
    ],
    trustLabel: "이유식 후기",
    featuredReason: "씹는 연습을 시작하는 후기용 부드러운 진밥",
    difficulty: 1,
    cookingTime: 28,
    servings: 1,
    beginnerSummary: "후기는 하루 3회 식사 리듬과 씹는 연습이 중요합니다. 두부는 알레르기 표시 식품이므로 처음이라면 소량부터 확인하세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "두부와 감자가 들어간 부드러운 진밥",
    imageCaption: "밥알이 보이지만 잇몸으로 쉽게 으깨지는 질감으로 맞춥니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "감자와 양파는 잘게 썰고 두부는 데쳐서 작은 큐브로 자릅니다.",
        imageUrl: null,
        beginnerTip: "두부는 너무 작게 으깨면 질감 연습이 줄어드니 후기에는 조금 남겨도 됩니다.",
        visualCue: "재료가 쌀알 2~3개 크기 정도면 좋습니다.",
      },
      {
        index: 2,
        description: "쌀과 물을 넣고 약불에서 15분 끓인 뒤 감자와 양파를 넣습니다.",
        imageUrl: null,
        beginnerTip: "감자가 익으면서 죽이 되직해질 수 있으니 물을 조금 남겨둡니다.",
        visualCue: "감자를 눌렀을 때 쉽게 으깨지면 익은 상태입니다.",
      },
      {
        index: 3,
        description: "두부를 넣고 3분 더 끓이며 숟가락으로 가볍게 으깹니다.",
        imageUrl: null,
        beginnerTip: "두부를 넣은 뒤 세게 저으면 완전히 부서질 수 있습니다.",
        visualCue: "두부 조각이 보이지만 숟가락으로 눌러지는 정도면 됩니다.",
      },
      {
        index: 4,
        description: "뜨거운 김을 빼고 한입 양씩 천천히 먹입니다.",
        imageUrl: null,
        beginnerTip: "후기에는 아기가 씹을 시간을 충분히 갖도록 급하게 먹이지 않습니다.",
        visualCue: "숟가락을 세웠을 때 천천히 퍼지는 진밥 농도면 됩니다.",
      },
    ],
  },
  {
    id: "curated-baby-egg-yolk-vegetable-soft-rice",
    name: "후기 노른자채소진밥",
    category: "이유식",
    method: "끓이기",
    calories: "118",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-egg-yolk-vegetable-soft-rice.png",
    ingredients: "쌀, 계란, 당근, 청경채",
    hashTag: "#후기이유식 #노른자 #채소진밥 #알레르기확인",
    ingredientList: ["쌀", "계란", "당근", "청경채"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 40g", "후기 진밥 기준입니다."),
      ingredient("완숙 계란노른자", "1/2개", "달걀은 알레르기 유발 식품이라 완숙 노른자부터 확인합니다.", "흰자는 아기 단계에 맞춰 별도 상담/확인 후 진행하세요."),
      ingredient("당근", "15g", "작게 썰어 충분히 익히면 단맛이 납니다."),
      ingredient("청경채", "10g", "잎 부분 위주로 잘게 다집니다.", "질긴 줄기는 제거하세요."),
    ],
    trustLabel: "이유식 후기",
    featuredReason: "달걀 노른자와 채소를 더한 후기 씹기 연습 진밥",
    difficulty: 1,
    cookingTime: 26,
    servings: 1,
    beginnerSummary: "달걀은 대표 알레르기 식품입니다. 처음 먹이는 경우 완숙 노른자를 소량부터 시작하고, 섭취 후 두드러기·구토·호흡 증상이 있으면 중단하고 진료를 받으세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "노른자와 채소가 섞인 후기 이유식 진밥",
    imageCaption: "노른자는 완숙으로 익혀 잘게 풀어 넣습니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "계란은 완숙으로 삶고 노른자만 분리해 곱게 으깹니다.",
        imageUrl: null,
        beginnerTip: "반숙은 피하고 완전히 익힌 노른자를 사용합니다.",
        visualCue: "노른자 가운데까지 보슬보슬하게 익었으면 완숙입니다.",
      },
      {
        index: 2,
        description: "당근과 청경채는 잘게 다져 쌀과 함께 무르게 끓입니다.",
        imageUrl: null,
        beginnerTip: "청경채 줄기는 질길 수 있어 잎 위주로 시작하세요.",
        visualCue: "당근이 숟가락으로 쉽게 눌리면 충분히 익은 상태입니다.",
      },
      {
        index: 3,
        description: "완성 직전 으깬 노른자를 넣고 1분 더 섞어 익힙니다.",
        imageUrl: null,
        beginnerTip: "노른자를 오래 끓이면 퍽퍽해질 수 있어 마지막에 넣습니다.",
        visualCue: "노른자 색이 진밥 전체에 고르게 퍼지면 됩니다.",
      },
      {
        index: 4,
        description: "미지근하게 식힌 뒤 소량부터 먹이며 반응을 확인합니다.",
        imageUrl: null,
        beginnerTip: "알레르기 확인이 필요한 재료는 오전 식사에 시도하면 관찰하기 쉽습니다.",
        visualCue: "한입 크기가 작고 재료 입자가 손으로 쉽게 으깨지면 좋습니다.",
      },
    ],
  },
  {
    id: "curated-baby-beef-bokchoy-soft-rice",
    name: "완료기 소고기청경채진밥",
    category: "이유식",
    method: "끓이기",
    calories: "156",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-beef-bokchoy-soft-rice.png",
    ingredients: "쌀, 소고기, 청경채, 당근",
    hashTag: "#완료기이유식 #소고기 #청경채 #진밥",
    ingredientList: ["쌀", "소고기", "청경채", "당근"],
    ingredientDetails: [
      ingredient("쌀", "불린 쌀 45g", "완료기는 무른밥에서 유아식으로 넘어가는 단계입니다."),
      ingredient("소고기", "20g", "기름 적은 부위를 잘게 다져 완전히 익힙니다."),
      ingredient("청경채", "15g", "잎 위주로 잘게 다지면 씹기 쉽습니다."),
      ingredient("당근", "15g", "색과 단맛을 더하는 채소입니다.", "푹 익혀 작게 자르세요."),
    ],
    trustLabel: "이유식 완료기",
    featuredReason: "가족 식사 리듬으로 넘어가기 전 연습하기 좋은 한 끼 진밥",
    difficulty: 1,
    cookingTime: 28,
    servings: 1,
    beginnerSummary: "완료기라도 성인식처럼 간하지 않습니다. 큰 덩어리, 질긴 고기, 둥근 조각은 질식 위험이 있어 작고 부드럽게 준비하세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "소고기와 청경채가 들어간 완료기 진밥",
    imageCaption: "재료 모양은 보이되 잇몸으로 씹을 수 있게 충분히 부드럽게 익힙니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "소고기, 청경채, 당근을 아기 한입보다 훨씬 작게 다집니다.",
        imageUrl: null,
        beginnerTip: "둥글거나 큰 조각은 목에 걸릴 수 있어 길고 얇거나 작게 자릅니다.",
        visualCue: "재료가 밥알 몇 개 크기로 잘게 보이면 됩니다.",
      },
      {
        index: 2,
        description: "쌀과 물을 넣고 무른밥 농도가 되도록 약불에서 끓입니다.",
        imageUrl: null,
        beginnerTip: "완료기라도 아이가 피곤하거나 아프면 농도를 다시 묽게 조절할 수 있습니다.",
        visualCue: "밥알 모양이 남고 국물이 거의 없어지면 진밥에 가깝습니다.",
      },
      {
        index: 3,
        description: "소고기와 당근을 먼저 넣어 익힌 뒤 청경채를 넣고 마무리합니다.",
        imageUrl: null,
        beginnerTip: "청경채는 오래 끓이면 색과 향이 떨어지므로 마지막에 넣습니다.",
        visualCue: "소고기가 완전히 갈색이고 당근이 쉽게 으깨지면 됩니다.",
      },
      {
        index: 4,
        description: "덩어리를 한 번 더 확인하고 미지근하게 식혀 제공합니다.",
        imageUrl: null,
        beginnerTip: "식사 중에는 반드시 옆에서 지켜보고 천천히 먹게 합니다.",
        visualCue: "숟가락으로 눌렀을 때 모든 재료가 쉽게 으깨지면 좋습니다.",
      },
    ],
  },
  {
    id: "curated-baby-sweet-potato-apple-mash",
    name: "완료기 고구마사과매시",
    category: "이유식",
    method: "으깨기",
    calories: "104",
    thumbnailUrl: "/images/recipes/jipbab-curated/baby-sweet-potato-apple-mash.png",
    ingredients: "고구마, 사과, 요거트",
    hashTag: "#완료기이유식 #간식 #고구마 #사과",
    ingredientList: ["고구마", "사과", "요거트"],
    ingredientDetails: [
      ingredient("고구마", "60g", "푹 찌면 설탕 없이도 단맛이 납니다."),
      ingredient("사과", "30g", "딱딱한 생사과는 익히거나 아주 잘게 다져 사용합니다.", "껍질과 씨는 제거하세요."),
      ingredient("무가당 플레인요거트", "1큰술", "우유 알레르기 반응을 확인한 뒤 사용합니다."),
      ingredient("끓인 물", "1큰술", "되직하면 농도 조절용으로 소량 넣습니다."),
    ],
    trustLabel: "이유식 완료기",
    featuredReason: "설탕 없이 단맛을 내는 완료기 간식형 이유식",
    difficulty: 1,
    cookingTime: 18,
    servings: 1,
    beginnerSummary: "고구마와 사과는 충분히 익히고 무가당 요거트를 씁니다. 꿀은 12개월 전에는 금지이며, 완료기에도 처음 주는 재료는 반응을 확인하세요.",
    measurementTips: BABY_FOOD_MEASUREMENT_TIPS,
    imageAlt: "고구마와 사과를 으깬 완료기 이유식 간식",
    imageCaption: "덩어리가 크지 않게 으깨고 요거트는 무가당으로 고릅니다.",
    ...BABY_FOOD_SOURCE,
    steps: [
      {
        index: 1,
        description: "고구마는 껍질을 벗겨 푹 찌고 사과는 껍질과 씨를 제거해 익힙니다.",
        imageUrl: null,
        beginnerTip: "사과는 생으로 크게 주면 질식 위험이 있어 익히거나 아주 잘게 준비합니다.",
        visualCue: "고구마와 사과가 포크로 쉽게 눌리면 충분히 익은 상태입니다.",
      },
      {
        index: 2,
        description: "고구마와 사과를 따뜻할 때 포크로 곱게 으깹니다.",
        imageUrl: null,
        beginnerTip: "완료기라도 큰 덩어리는 남기지 않는 편이 안전합니다.",
        visualCue: "알갱이가 작고 촉촉한 매시처럼 보이면 됩니다.",
      },
      {
        index: 3,
        description: "무가당 플레인요거트 1큰술을 섞고 되직하면 끓인 물을 더합니다.",
        imageUrl: null,
        beginnerTip: "가당 요거트나 꿀은 넣지 않습니다.",
        visualCue: "숟가락에 떠서 천천히 떨어지는 농도면 먹이기 쉽습니다.",
      },
      {
        index: 4,
        description: "한 김 식힌 뒤 간식 양으로 소량 제공합니다.",
        imageUrl: null,
        beginnerTip: "간식은 식사를 밀어내지 않도록 적은 양부터 시작합니다.",
        visualCue: "아기가 혀로 밀어내지 않고 천천히 삼키면 질감이 맞는 편입니다.",
      },
    ],
  },
];

export const CURATED_JIPBAB_RECIPES: CuratedRecipe[] = [
  ...BASE_CURATED_JIPBAB_RECIPES,
  ...EASY_RECIPE_EXPANSION,
].map((recipe) => ({
  ...recipe,
  guideImageUrl: `/images/recipes/jipbab-curated/guides/${recipe.id}-recipe-card.svg`,
}));

export const CURATED_RECIPE_RECORDS: RecipeRecord[] = CURATED_JIPBAB_RECIPES.map((recipe) => ({
  id: recipe.id,
  name: recipe.name,
  category: recipe.category,
  method: recipe.method,
  calories: recipe.calories,
  thumbnailUrl: recipe.thumbnailUrl,
  ingredients: recipe.ingredients,
  hashTag: recipe.hashTag,
}));

export function findCuratedRecipe(recipeId: string): CuratedRecipe | null {
  return CURATED_JIPBAB_RECIPES.find((recipe) => recipe.id === recipeId) ?? null;
}
