// 이 파일은 경쟁 앱 대비 첫 체감 품질을 높이기 위한 한국 집밥 큐레이션 레시피를 제공합니다.
import type { RecipeDetailRecord, RecipeRecord } from "@/types";

export type CuratedRecipe = RecipeDetailRecord & {
  trustLabel: string;
  featuredReason: string;
};

export const CURATED_JIPBAB_RECIPES: CuratedRecipe[] = [
  {
    id: "curated-kimchi-fried-rice",
    name: "김치볶음밥",
    category: "밥",
    method: "볶기",
    calories: "520",
    thumbnailUrl: "/images/recipes/kimchi-fried-rice.png",
    ingredients: "김치, 밥, 계란, 대파, 참기름",
    hashTag: "#한그릇 #냉장고파먹기",
    ingredientList: ["김치", "밥", "계란", "대파", "참기름"],
    trustLabel: "집밥 기본",
    featuredReason: "김치와 계란만 있어도 바로 만들 수 있는 국민 한 그릇",
    steps: [
      { index: 1, description: "김치는 먹기 좋은 크기로 자르고 대파는 송송 썰어 준비합니다.", imageUrl: null },
      { index: 2, description: "팬에 기름을 두르고 대파를 먼저 볶아 향을 냅니다.", imageUrl: null },
      { index: 3, description: "김치를 넣고 충분히 볶은 뒤 밥을 넣어 고르게 섞습니다.", imageUrl: null },
      { index: 4, description: "참기름을 둘러 마무리하고 계란프라이를 올립니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-doenjang-jjigae",
    name: "된장찌개",
    category: "국·찌개",
    method: "끓이기",
    calories: "290",
    thumbnailUrl: "/images/recipes/jipbab-curated/doenjang-jjigae-basic.png",
    ingredients: "된장, 두부, 애호박, 양파, 대파",
    hashTag: "#국물 #집밥",
    ingredientList: ["된장", "두부", "애호박", "양파", "대파"],
    trustLabel: "집밥 기본",
    featuredReason: "두부와 양파를 소진하기 좋은 가장 익숙한 찌개",
    steps: [
      { index: 1, description: "냄비에 물을 붓고 된장을 풀어 끓입니다.", imageUrl: null },
      { index: 2, description: "애호박과 양파를 넣고 중불에서 익힙니다.", imageUrl: null },
      { index: 3, description: "두부와 대파를 넣고 한소끔 더 끓입니다.", imageUrl: null },
      { index: 4, description: "간을 보고 부족하면 된장을 조금 더 풀어 마무리합니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-gyeran-mari",
    name: "계란말이",
    category: "반찬",
    method: "부치기",
    calories: "260",
    thumbnailUrl: "/images/recipes/jipbab-curated/gyeran-mari-basic.png",
    ingredients: "계란, 대파, 당근, 소금, 식용유",
    hashTag: "#반찬 #도시락",
    ingredientList: ["계란", "대파", "당근", "소금", "식용유"],
    trustLabel: "집밥 기본",
    featuredReason: "계란 소진과 반찬 준비를 동시에 해결",
    steps: [
      { index: 1, description: "계란을 풀고 잘게 썬 대파와 당근, 소금을 섞습니다.", imageUrl: null },
      { index: 2, description: "약불 팬에 계란물을 얇게 붓고 끝부터 말아줍니다.", imageUrl: null },
      { index: 3, description: "남은 계란물을 조금씩 부어가며 반복해서 두껍게 말아줍니다.", imageUrl: null },
      { index: 4, description: "한 김 식힌 뒤 먹기 좋은 크기로 썹니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-dubu-jorim",
    name: "두부조림",
    category: "반찬",
    method: "조리기",
    calories: "310",
    thumbnailUrl: "/images/recipes/jipbab-curated/dubu-jorim-basic.png",
    ingredients: "두부, 간장, 대파, 고춧가루, 마늘",
    hashTag: "#두부 #밑반찬",
    ingredientList: ["두부", "간장", "대파", "고춧가루", "마늘"],
    trustLabel: "집밥 기본",
    featuredReason: "유통기한 짧은 두부를 가장 빨리 처리하는 반찬",
    steps: [
      { index: 1, description: "두부는 물기를 닦고 도톰하게 썹니다.", imageUrl: null },
      { index: 2, description: "팬에 두부를 앞뒤로 노릇하게 굽습니다.", imageUrl: null },
      { index: 3, description: "간장, 고춧가루, 마늘, 대파로 양념장을 만듭니다.", imageUrl: null },
      { index: 4, description: "두부 위에 양념장을 얹고 약불에서 자작하게 조립니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-pork-kimchi-jjigae",
    name: "돼지고기 김치찌개",
    category: "국·찌개",
    method: "끓이기",
    calories: "430",
    thumbnailUrl: "/images/recipes/jipbab-curated/pork-kimchi-jjigae-basic.png",
    ingredients: "김치, 돼지고기, 두부, 대파, 고춧가루",
    hashTag: "#김치찌개 #저녁메뉴",
    ingredientList: ["김치", "돼지고기", "두부", "대파", "고춧가루"],
    trustLabel: "저녁 추천",
    featuredReason: "김치와 두부가 있을 때 만족도가 높은 메인 메뉴",
    steps: [
      { index: 1, description: "냄비에 돼지고기와 김치를 넣고 먼저 볶습니다.", imageUrl: null },
      { index: 2, description: "물을 붓고 고춧가루를 더해 중불에서 끓입니다.", imageUrl: null },
      { index: 3, description: "두부와 대파를 넣고 5분 더 끓입니다.", imageUrl: null },
      { index: 4, description: "김치의 짠맛에 맞춰 간을 조절합니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-gamja-jorim",
    name: "감자조림",
    category: "반찬",
    method: "조리기",
    calories: "250",
    thumbnailUrl: "/images/recipes/jipbab-curated/gamja-jorim-basic.png",
    ingredients: "감자, 간장, 설탕, 식용유, 참기름",
    hashTag: "#감자 #밑반찬",
    ingredientList: ["감자", "간장", "설탕", "식용유", "참기름"],
    trustLabel: "밑반찬",
    featuredReason: "상온 재료와 기본 양념만으로 만들기 쉬운 반찬",
    steps: [
      { index: 1, description: "감자는 한입 크기로 썰어 물에 잠시 담가 전분을 뺍니다.", imageUrl: null },
      { index: 2, description: "팬에 기름을 두르고 감자를 가볍게 볶습니다.", imageUrl: null },
      { index: 3, description: "간장, 설탕, 물을 넣고 뚜껑을 덮어 익힙니다.", imageUrl: null },
      { index: 4, description: "국물이 거의 졸면 참기름을 둘러 마무리합니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-soy-garlic-chicken",
    name: "간장마늘 닭조림",
    category: "일품",
    method: "조리기",
    calories: "610",
    thumbnailUrl: "/images/recipes/soy-garlic-chicken.png",
    ingredients: "닭고기, 간장, 마늘, 양파, 대파",
    hashTag: "#닭고기 #메인반찬",
    ingredientList: ["닭고기", "간장", "마늘", "양파", "대파"],
    trustLabel: "저녁 추천",
    featuredReason: "냉장고 채소를 곁들여 메인 요리로 만들기 좋음",
    steps: [
      { index: 1, description: "닭고기는 키친타월로 물기를 제거합니다.", imageUrl: null },
      { index: 2, description: "팬에 닭고기를 굽고 양파와 마늘을 넣어 볶습니다.", imageUrl: null },
      { index: 3, description: "간장 양념과 물을 넣고 중약불에서 조립니다.", imageUrl: null },
      { index: 4, description: "대파를 넣고 윤기가 날 때까지 마무리합니다.", imageUrl: null },
    ],
  },
  {
    id: "curated-tuna-kimchi-fried-rice",
    name: "참치김치볶음밥",
    category: "밥",
    method: "볶기",
    calories: "560",
    thumbnailUrl: "/images/recipes/jipbab-curated/tuna-kimchi-fried-rice.png",
    ingredients: "참치캔, 김치, 밥, 대파, 계란",
    hashTag: "#참치캔 #한그릇",
    ingredientList: ["참치캔", "김치", "밥", "대파", "계란"],
    trustLabel: "한그릇",
    featuredReason: "캔참치와 남은 김치로 빠르게 해결하는 메뉴",
    steps: [
      { index: 1, description: "참치캔은 기름을 가볍게 빼고 김치는 잘게 썹니다.", imageUrl: null },
      { index: 2, description: "대파를 볶아 향을 낸 뒤 김치와 참치를 넣습니다.", imageUrl: null },
      { index: 3, description: "밥을 넣고 고르게 볶아 간을 맞춥니다.", imageUrl: null },
      { index: 4, description: "계란프라이를 올려 완성합니다.", imageUrl: null },
    ],
  },
];

export const CURATED_RECIPE_RECORDS: RecipeRecord[] = CURATED_JIPBAB_RECIPES.map((recipe) => ({
  id: recipe.id,
  name: recipe.name,
  category: recipe.category,
  method: recipe.method,
  calories: recipe.calories,
  thumbnailUrl: recipe.thumbnailUrl,
  ingredients: recipe.ingredients,
  hashTag: recipe.hashTag,
}));

export function findCuratedRecipe(recipeId: string): CuratedRecipe | null {
  return CURATED_JIPBAB_RECIPES.find((recipe) => recipe.id === recipeId) ?? null;
}
