import type {
  IngredientRecord,
  RecipeWithMatch,
  ShoppingItem,
} from "@/types";

const now = new Date().toISOString();

function toDateOnly(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function demoExpiryDate(daysFromToday: number): string {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + daysFromToday);
  return toDateOnly(date);
}

export const APPSTORE_DEMO_INGREDIENTS: IngredientRecord[] = [
  {
    id: "demo-onion",
    deviceId: "demo-device",
    userId: null,
    name: "양파",
    category: "채소",
    storageType: "냉장",
    quantity: "2개",
    expiryDate: demoExpiryDate(2),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-egg",
    deviceId: "demo-device",
    userId: null,
    name: "계란",
    category: "육류",
    storageType: "냉장",
    quantity: "10개",
    expiryDate: demoExpiryDate(4),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-tofu",
    deviceId: "demo-device",
    userId: null,
    name: "두부",
    category: "통조림/가공식품",
    storageType: "냉장",
    quantity: "1모",
    expiryDate: demoExpiryDate(1),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-green-onion",
    deviceId: "demo-device",
    userId: null,
    name: "대파",
    category: "채소",
    storageType: "냉장",
    quantity: "1단",
    expiryDate: demoExpiryDate(3),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-milk",
    deviceId: "demo-device",
    userId: null,
    name: "우유",
    category: "유제품",
    storageType: "냉장",
    quantity: "1팩",
    expiryDate: demoExpiryDate(5),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-kimchi",
    deviceId: "demo-device",
    userId: null,
    name: "김치",
    category: "통조림/가공식품",
    storageType: "냉장",
    quantity: "1통",
    expiryDate: demoExpiryDate(8),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-carrot",
    deviceId: "demo-device",
    userId: null,
    name: "당근",
    category: "채소",
    storageType: "냉장",
    quantity: "2개",
    expiryDate: demoExpiryDate(6),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-potato",
    deviceId: "demo-device",
    userId: null,
    name: "감자",
    category: "채소",
    storageType: "냉장",
    quantity: "3개",
    expiryDate: demoExpiryDate(9),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-apple",
    deviceId: "demo-device",
    userId: null,
    name: "사과",
    category: "과일",
    storageType: "냉장",
    quantity: "2개",
    expiryDate: demoExpiryDate(7),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "demo-pork",
    deviceId: "demo-device",
    userId: null,
    name: "돼지고기",
    category: "육류",
    storageType: "냉장",
    quantity: "300g",
    expiryDate: demoExpiryDate(1),
    barcode: null,
    imageUrl: null,
    memo: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const APPSTORE_DEMO_SHOPPING_ITEMS: ShoppingItem[] = [
  {
    id: "shop-garlic",
    deviceId: "demo-device",
    userId: null,
    name: "마늘",
    quantity: "1봉",
    category: "채소",
    checked: false,
    sourceRecipeId: "recipe-tofu-jjim",
    sourceRecipeName: "새우 두부 계란찜",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shop-shrimp",
    deviceId: "demo-device",
    userId: null,
    name: "새우",
    quantity: "1팩",
    category: "수산물",
    checked: false,
    sourceRecipeId: "recipe-tofu-jjim",
    sourceRecipeName: "새우 두부 계란찜",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "shop-salt",
    deviceId: "demo-device",
    userId: null,
    name: "소금",
    quantity: "1통",
    category: "조미료",
    checked: true,
    sourceRecipeId: null,
    sourceRecipeName: null,
    createdAt: now,
    updatedAt: now,
  },
];

export const APPSTORE_DEMO_RECIPES: RecipeWithMatch[] = [
  {
    id: "recipe-tofu-jjim",
    name: "새우 두부 계란찜",
    category: "반찬",
    method: "찌기",
    calories: "220 kcal",
    thumbnailUrl: "/images/recipes/jipbab-curated/dubu-jorim-basic.png",
    ingredients: "두부, 계란, 새우, 대파, 소금",
    hashTag: "#집밥 #계란찜",
    matchRate: 60,
    matchedIngredients: ["두부", "계란", "대파"],
    missingIngredients: ["새우", "소금"],
    totalRecipeIngredients: 5,
    ingredientList: ["두부", "계란", "새우", "대파", "소금"],
  },
  {
    id: "recipe-onion-egg",
    name: "양파 계란덮밥",
    category: "한식",
    method: "볶기",
    calories: "410 kcal",
    thumbnailUrl: "/images/recipes/kimchi-fried-rice.png",
    ingredients: "양파, 계란, 대파, 간장, 밥",
    hashTag: "#한그릇",
    matchRate: 60,
    matchedIngredients: ["양파", "계란", "대파"],
    missingIngredients: ["간장", "밥"],
    totalRecipeIngredients: 5,
    ingredientList: ["양파", "계란", "대파", "간장", "밥"],
  },
  {
    id: "recipe-tofu-soup",
    name: "두부 대파국",
    category: "국·찌개",
    method: "끓이기",
    calories: "180 kcal",
    thumbnailUrl: "/images/recipes/jipbab-curated/doenjang-jjigae-basic.png",
    ingredients: "두부, 대파, 양파, 소금",
    hashTag: "#국 #두부국",
    matchRate: 75,
    matchedIngredients: ["두부", "대파", "양파"],
    missingIngredients: ["소금"],
    totalRecipeIngredients: 4,
    ingredientList: ["두부", "대파", "양파", "소금"],
  },
  {
    id: "recipe-egg-roll",
    name: "대파 달걀말이",
    category: "반찬",
    method: "부치기",
    calories: "250 kcal",
    thumbnailUrl: "/images/recipes/jipbab-curated/gyeran-mari-basic.png",
    ingredients: "계란, 대파, 양파, 소금",
    hashTag: "#달걀말이",
    matchRate: 75,
    matchedIngredients: ["계란", "대파", "양파"],
    missingIngredients: ["소금"],
    totalRecipeIngredients: 4,
    ingredientList: ["계란", "대파", "양파", "소금"],
  },
  {
    id: "recipe-salad",
    name: "오렌지와 당근 만남주스",
    category: "디저트",
    method: "기타",
    calories: "150 kcal",
    thumbnailUrl: "/images/ingredients/orange-juice-photo.png",
    ingredients: "오렌지, 당근, 요거트",
    hashTag: "#주스",
    matchRate: 0,
    matchedIngredients: [],
    missingIngredients: ["오렌지", "당근", "요거트"],
    totalRecipeIngredients: 3,
    ingredientList: ["오렌지", "당근", "요거트"],
  },
];
