// 이 파일은 소셜/공개 레시피 트렌드를 참고해 집밥노트가 직접 작성한 쉬운 레시피 확장 묶음입니다.
import type { CuratedRecipe } from "./curated-recipes.ts";
import type { RecipeDetailStep, RecipeIngredientDetail } from "@/types";

const EASY_MEASUREMENT_TIPS = [
  "1큰술 = 밥숟가락 평평하게 1번 = 약 15ml",
  "1작은술 = 티스푼 평평하게 1번 = 약 5ml",
  "1컵 = 일반 종이컵 1컵 = 약 180ml",
  "한꼬집 = 엄지와 검지로 아주 조금 집은 양",
];

const EASY_RECIPE_SOURCE = {
  sourceProvider: "집밥노트",
  sourceExternalId: "easy-recipe-expansion-2026-06",
  sourceUrl: "https://www.10000recipe.com",
  sourceAttribution: "인스타그램 공개 해시태그 흐름과 만개의레시피식 쉬운 메뉴 패턴 참고, 집밥노트 직접 작성",
  sourceLicense: "외부 원문/이미지 미복사, 집밥노트 원본 콘텐츠",
  contentOrigin: "original" as const,
  reviewedForBeginner: true,
};

type EasyIngredient = {
  name: string;
  display: string;
  note?: string;
  prep?: string;
};

type EasyRecipeSpec = {
  id: string;
  name: string;
  category: string;
  method: string;
  calories: string;
  cookingTime: number;
  servings: number;
  trustLabel: string;
  featuredReason: string;
  beginnerSummary: string;
  ingredients: EasyIngredient[];
  safetyNote?: string;
  imageTone: string;
};

function ingredientDetail(item: EasyIngredient): RecipeIngredientDetail {
  return {
    name: item.name,
    display: item.display,
    beginnerNote: item.note ?? null,
    prepNote: item.prep ?? null,
  };
}

function buildSteps(spec: EasyRecipeSpec): RecipeDetailStep[] {
  const mainIngredient = spec.ingredients[0]?.name ?? spec.name;
  const secondIngredient = spec.ingredients[1]?.name ?? "재료";
  const seasoning = spec.ingredients.at(-1)?.name ?? "간";
  const isSoup = spec.category === "국·찌개" || spec.method.includes("끓");
  const isRice = spec.category === "밥" || spec.name.includes("덮밥") || spec.name.includes("볶음밥");
  const isJeon = spec.method.includes("부치") || spec.name.includes("전");

  return [
    {
      index: 1,
      description: `${mainIngredient}와 ${secondIngredient}를 씻고 한입보다 작게 준비합니다.`,
      imageUrl: null,
      beginnerTip: "칼이 서툴면 어른에게 첫 손질만 부탁하고, 자른 재료부터 조리해도 됩니다.",
      visualCue: "재료 크기가 서로 비슷하면 익는 속도가 맞아서 실패가 줄어듭니다.",
    },
    {
      index: 2,
      description: isSoup
        ? "냄비에 물 또는 육수를 넣고 단단한 재료부터 약불에서 끓입니다."
        : isJeon
          ? "팬에 기름을 얇게 두르고 반죽이나 재료를 숟가락 크기로 올립니다."
          : "팬을 중불로 달군 뒤 기름을 조금 두르고 단단한 재료부터 볶습니다.",
      imageUrl: null,
      beginnerTip: isSoup
        ? "물이 끓어오르면 불을 중약불로 낮추면 넘치지 않습니다."
        : "기름은 많이 넣지 말고 팬 표면이 살짝 반짝일 정도면 충분합니다.",
      visualCue: isSoup
        ? "작은 거품이 계속 올라오면 알맞게 끓는 상태입니다."
        : "재료 가장자리가 투명하거나 연한 갈색이 되면 다음 단계로 넘어갑니다.",
    },
    {
      index: 3,
      description: `${seasoning}을 넣고 전체를 골고루 섞어 ${spec.method}합니다.`,
      imageUrl: null,
      beginnerTip: "간은 처음부터 많이 넣지 말고 절반만 넣은 뒤 마지막에 맛을 보세요.",
      visualCue: isRice
        ? "밥알과 재료 색이 고르게 섞이면 거의 완성입니다."
        : "재료 겉면에 양념이 얇게 묻고 물기가 자작하게 줄면 좋습니다.",
    },
    {
      index: 4,
      description: "불을 끄고 1분 식힌 뒤 그릇에 담아 먹기 좋은 온도로 냅니다.",
      imageUrl: null,
      beginnerTip: spec.safetyNote ?? "아이와 함께 먹는 메뉴는 뜨거운 김을 충분히 빼고 제공합니다.",
      visualCue: "한 숟가락 떠도 흐트러지지 않고, 재료가 쉽게 씹히면 완성입니다.",
    },
  ];
}

function makeRecipe(spec: EasyRecipeSpec): CuratedRecipe {
  const ingredientList = spec.ingredients.map((item) => item.name);

  return {
    id: spec.id,
    name: spec.name,
    category: spec.category,
    method: spec.method,
    calories: spec.calories,
    thumbnailUrl: `/images/recipes/jipbab-curated/easy/${spec.id}.png`,
    ingredients: ingredientList.join(", "),
    hashTag: `#쉬운집밥 #초보가능 #${spec.trustLabel.replace(/\s+/g, "")}`,
    ingredientList,
    ingredientDetails: spec.ingredients.map(ingredientDetail),
    trustLabel: spec.trustLabel,
    featuredReason: spec.featuredReason,
    difficulty: 1,
    cookingTime: spec.cookingTime,
    servings: spec.servings,
    beginnerSummary: `${spec.beginnerSummary} 초등학생이나 중학생도 따라할 수 있도록 불 세기와 재료 크기를 먼저 맞추는 레시피입니다.`,
    measurementTips: EASY_MEASUREMENT_TIPS,
    imageAlt: `${spec.name} 완성 사진`,
    imageCaption: spec.imageTone,
    ...EASY_RECIPE_SOURCE,
    steps: buildSteps(spec),
  };
}

const EASY_RECIPE_SPECS: EasyRecipeSpec[] = [
  {
    id: "easy-dubu-vegetable-jeon",
    name: "두부야채전",
    category: "아이반찬",
    method: "부치기",
    calories: "190",
    cookingTime: 18,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "두부와 냉장고 채소를 한 번에 쓰는 부드러운 전",
    beginnerSummary: "두부 물기만 잘 빼면 팬에서 부서지는 일이 크게 줄어듭니다.",
    safetyNote: "달걀 알레르기가 있으면 달걀 없이 전분을 조금 늘려 주세요.",
    imageTone: "작게 부친 두부야채전이 접시에 가지런히 담긴 완성 모습",
    ingredients: [
      { name: "두부", display: "1/2모", note: "키친타월로 물기를 눌러 빼면 반죽이 단단해져요." },
      { name: "계란", display: "1개", note: "반죽을 붙이는 역할입니다." },
      { name: "당근", display: "2큰술", prep: "잘게 다져야 아이가 먹기 편합니다." },
      { name: "부침가루", display: "2큰술", note: "질면 1큰술 더 넣어도 됩니다." },
    ],
  },
  {
    id: "easy-enoki-egg-jeon",
    name: "팽이버섯계란전",
    category: "아이반찬",
    method: "부치기",
    calories: "170",
    cookingTime: 12,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "팽이버섯을 짧게 잘라 계란에 섞는 초간단 반찬",
    beginnerSummary: "팽이버섯은 길게 남기면 먹기 불편하니 1cm 길이로 잘라 주세요.",
    safetyNote: "버섯 줄기가 길게 남지 않도록 잘게 잘라 제공합니다.",
    imageTone: "노릇한 계란전 사이로 잘게 자른 팽이버섯이 보이는 완성 모습",
    ingredients: [
      { name: "팽이버섯", display: "1/2봉", prep: "밑동을 자르고 1cm로 썰어요." },
      { name: "계란", display: "2개", note: "완전히 풀어야 전이 부드럽습니다." },
      { name: "양파", display: "2큰술", prep: "아주 잘게 다집니다." },
      { name: "식용유", display: "1큰술", note: "팬에 얇게 펴 바릅니다." },
    ],
  },
  {
    id: "easy-broccoli-corn-jeon",
    name: "브로콜리옥수수전",
    category: "아이반찬",
    method: "부치기",
    calories: "210",
    cookingTime: 18,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "초록 채소를 달콤한 옥수수와 섞어 먹기 쉽게 만든 전",
    beginnerSummary: "브로콜리는 먼저 데쳐야 풋내가 줄고 반죽 안에서도 잘 익습니다.",
    safetyNote: "어린 아이에게는 옥수수 알갱이를 한 번 더 다져 주세요.",
    imageTone: "초록 브로콜리와 노란 옥수수가 보이는 작은 전 완성 모습",
    ingredients: [
      { name: "브로콜리", display: "1/2컵", prep: "데친 뒤 송이 부분을 잘게 다집니다." },
      { name: "옥수수", display: "3큰술", note: "물기를 빼고 씁니다." },
      { name: "계란", display: "1개", note: "반죽을 묶어 줍니다." },
      { name: "부침가루", display: "3큰술", note: "숟가락으로 떠질 정도 농도면 됩니다." },
    ],
  },
  {
    id: "easy-potato-stir-fry",
    name: "감자채볶음",
    category: "아이반찬",
    method: "볶기",
    calories: "160",
    cookingTime: 15,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "감자 하나로 만드는 가장 기본적인 아이 반찬",
    beginnerSummary: "감자를 너무 두껍게 썰면 오래 걸리니 얇게 채 써는 것이 핵심입니다.",
    imageTone: "얇은 감자채와 당근채가 부드럽게 볶인 완성 모습",
    ingredients: [
      { name: "감자", display: "1개", prep: "얇게 채 썰고 물에 5분 담가 전분을 빼요." },
      { name: "당근", display: "1/4개", prep: "감자와 비슷한 두께로 썹니다." },
      { name: "양파", display: "1/4개", note: "단맛을 더합니다." },
      { name: "소금", display: "한꼬집", note: "아이용은 아주 조금만 넣습니다." },
    ],
  },
  {
    id: "easy-cucumber-sesame-muchim",
    name: "오이참깨무침",
    category: "아이반찬",
    method: "무치기",
    calories: "60",
    cookingTime: 8,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "불 없이 바로 만드는 아삭한 저자극 반찬",
    beginnerSummary: "오이를 얇게 썰면 양념이 빨리 배고 아이가 씹기 쉽습니다.",
    safetyNote: "어린 아이에게는 반달 모양으로 얇게 썰어 주세요.",
    imageTone: "참깨가 뿌려진 연한 오이무침 완성 모습",
    ingredients: [
      { name: "오이", display: "1개", prep: "반달 모양으로 얇게 썹니다." },
      { name: "참깨", display: "1작은술", note: "고소한 향을 냅니다." },
      { name: "참기름", display: "1작은술", note: "조금만 넣어도 향이 충분합니다." },
      { name: "식초", display: "1작은술", note: "새콤함이 싫으면 빼도 됩니다." },
    ],
  },
  {
    id: "easy-spinach-tofu-muchim",
    name: "시금치두부무침",
    category: "아이반찬",
    method: "무치기",
    calories: "130",
    cookingTime: 12,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "시금치를 두부와 섞어 부드럽게 먹이는 반찬",
    beginnerSummary: "시금치는 데친 뒤 물기를 꼭 짜야 무침이 질척하지 않습니다.",
    safetyNote: "대두 알레르기가 있으면 두부 대신 감자를 으깨 넣어도 됩니다.",
    imageTone: "초록 시금치와 하얀 두부가 부드럽게 섞인 무침",
    ingredients: [
      { name: "시금치", display: "1줌", prep: "끓는 물에 30초 데칩니다." },
      { name: "두부", display: "1/3모", prep: "데친 뒤 으깨 물기를 빼요." },
      { name: "참기름", display: "1작은술", note: "고소한 향을 냅니다." },
      { name: "깨", display: "1작은술", note: "마지막에 뿌립니다." },
    ],
  },
  {
    id: "easy-radish-namul",
    name: "무나물볶음",
    category: "아이반찬",
    method: "볶기",
    calories: "85",
    cookingTime: 15,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "무를 달큰하게 볶아 밥에 비벼 먹기 좋은 반찬",
    beginnerSummary: "무는 얇게 썰어야 빨리 익고 매운맛이 줄어듭니다.",
    imageTone: "부드럽게 익은 하얀 무나물이 작은 접시에 담긴 모습",
    ingredients: [
      { name: "무", display: "1컵", prep: "얇게 채 썹니다." },
      { name: "들기름", display: "1작은술", note: "없으면 참기름도 됩니다." },
      { name: "물", display: "3큰술", note: "무를 촉촉하게 익힙니다." },
      { name: "소금", display: "한꼬집", note: "마지막에 아주 조금만 넣습니다." },
    ],
  },
  {
    id: "easy-low-salt-anchovy-bokkeum",
    name: "아기멸치볶음",
    category: "아이반찬",
    method: "볶기",
    calories: "150",
    cookingTime: 10,
    servings: 3,
    trustLabel: "아이반찬",
    featuredReason: "잔멸치를 짜지 않게 볶아 밥반찬으로 쓰기 좋음",
    beginnerSummary: "잔멸치는 먼저 마른 팬에 볶으면 비린 향이 줄어듭니다.",
    safetyNote: "아이용은 잔가시와 딱딱한 큰 멸치를 골라냅니다.",
    imageTone: "작고 고슬고슬한 잔멸치볶음 완성 모습",
    ingredients: [
      { name: "잔멸치", display: "1컵", prep: "체에 털어 가루를 제거합니다." },
      { name: "올리고당", display: "1작은술", note: "윤기를 냅니다." },
      { name: "간장", display: "1작은술", note: "저염으로 아주 조금만 씁니다." },
      { name: "식용유", display: "1작은술", note: "마른 팬이 걱정될 때만 넣습니다." },
    ],
  },
  {
    id: "easy-quail-egg-jorim",
    name: "메추리알장조림 순한맛",
    category: "아이반찬",
    method: "조리기",
    calories: "220",
    cookingTime: 18,
    servings: 3,
    trustLabel: "아이반찬",
    featuredReason: "도시락과 밥반찬에 넣기 쉬운 순한 장조림",
    beginnerSummary: "간장물은 묽게 만들고 오래 졸이지 않아야 짜지 않습니다.",
    safetyNote: "어린 아이에게는 메추리알을 반 또는 4등분해 주세요.",
    imageTone: "윤기 나는 메추리알장조림이 작게 잘린 완성 모습",
    ingredients: [
      { name: "메추리알", display: "15개", prep: "껍질을 벗겨 준비합니다." },
      { name: "간장", display: "1큰술", note: "아이용은 적게 넣습니다." },
      { name: "물", display: "1컵", note: "짜지 않게 희석합니다." },
      { name: "양파", display: "1/4개", note: "단맛을 냅니다." },
    ],
  },
  {
    id: "easy-chicken-tender-soy-jorim",
    name: "닭안심간장조림",
    category: "아이반찬",
    method: "조리기",
    calories: "230",
    cookingTime: 18,
    servings: 2,
    trustLabel: "아이반찬",
    featuredReason: "닭안심을 부드럽게 익혀 아이 단백질 반찬으로 좋음",
    beginnerSummary: "닭안심은 너무 오래 익히면 퍽퍽해지니 중약불에서 촉촉하게 조립니다.",
    safetyNote: "닭고기는 속까지 하얗게 완전히 익혀야 합니다.",
    imageTone: "잘게 찢어도 부드러운 간장 닭안심조림 완성 모습",
    ingredients: [
      { name: "닭안심", display: "200g", prep: "힘줄을 제거하면 먹기 편합니다." },
      { name: "양파", display: "1/2개", note: "자연스러운 단맛을 냅니다." },
      { name: "간장", display: "1큰술", note: "처음에는 절반만 넣습니다." },
      { name: "물", display: "1/2컵", note: "촉촉하게 조립니다." },
    ],
  },
  {
    id: "easy-beef-vegetable-rice-ball",
    name: "소고기야채주먹밥",
    category: "밥",
    method: "비비기",
    calories: "360",
    cookingTime: 18,
    servings: 2,
    trustLabel: "아이한그릇",
    featuredReason: "밥, 소고기, 채소를 한입 크기로 뭉치는 든든한 메뉴",
    beginnerSummary: "재료를 잘게 볶은 뒤 밥과 섞으면 흘리지 않고 먹기 쉽습니다.",
    safetyNote: "아이 한입보다 작게 뭉치고, 고기는 완전히 익혀 주세요.",
    imageTone: "작은 소고기야채주먹밥이 접시에 둥글게 담긴 모습",
    ingredients: [
      { name: "밥", display: "1공기", note: "따뜻한 밥이 잘 뭉쳐집니다." },
      { name: "소고기", display: "80g", prep: "다짐육을 쓰면 쉽습니다." },
      { name: "당근", display: "2큰술", prep: "잘게 다져 볶습니다." },
      { name: "참기름", display: "1작은술", note: "마지막에 섞습니다." },
    ],
  },
  {
    id: "easy-egg-vegetable-fried-rice",
    name: "계란야채볶음밥",
    category: "밥",
    method: "볶기",
    calories: "430",
    cookingTime: 15,
    servings: 1,
    trustLabel: "아이한그릇",
    featuredReason: "찬밥과 계란, 자투리 채소로 만드는 기본 볶음밥",
    beginnerSummary: "밥은 마지막에 넣고 주걱으로 눌러 풀면 덩어리가 없어집니다.",
    safetyNote: "계란은 반숙 없이 완전히 익혀 주세요.",
    imageTone: "노란 계란과 잘게 썬 채소가 섞인 볶음밥 완성 모습",
    ingredients: [
      { name: "밥", display: "1공기", note: "찬밥이면 더 잘 볶아집니다." },
      { name: "계란", display: "1개", note: "스크램블처럼 먼저 익힙니다." },
      { name: "당근", display: "2큰술", prep: "작게 다집니다." },
      { name: "간장", display: "1작은술", note: "가장자리에서 살짝 끓이면 향이 납니다." },
    ],
  },
  {
    id: "easy-mild-beef-seaweed-soup",
    name: "소고기미역국 순한맛",
    category: "국·찌개",
    method: "끓이기",
    calories: "180",
    cookingTime: 25,
    servings: 2,
    trustLabel: "아이국",
    featuredReason: "미역을 잘게 잘라 아이도 먹기 쉬운 순한 국",
    beginnerSummary: "미역은 불리면 양이 많이 늘어나니 처음에는 조금만 써도 됩니다.",
    safetyNote: "미역을 길게 남기지 말고 짧게 잘라 주세요.",
    imageTone: "잘게 자른 미역과 소고기가 들어간 맑은 미역국",
    ingredients: [
      { name: "미역", display: "불린 것 1컵", prep: "짧게 자릅니다." },
      { name: "소고기", display: "80g", prep: "작게 썹니다." },
      { name: "물", display: "3컵", note: "국물 기준입니다." },
      { name: "국간장", display: "1작은술", note: "아이용은 아주 조금만 넣습니다." },
    ],
  },
  {
    id: "easy-potato-egg-soup",
    name: "감자계란국",
    category: "국·찌개",
    method: "끓이기",
    calories: "160",
    cookingTime: 15,
    servings: 2,
    trustLabel: "아이국",
    featuredReason: "감자와 계란만으로 끓이는 부드러운 아침국",
    beginnerSummary: "계란물은 마지막에 천천히 둘러야 국물이 탁해지지 않습니다.",
    safetyNote: "계란은 국물이 다시 끓을 때까지 완전히 익힙니다.",
    imageTone: "감자 조각과 부드러운 계란이 떠 있는 맑은 국",
    ingredients: [
      { name: "감자", display: "1개", prep: "얇은 반달로 썹니다." },
      { name: "계란", display: "1개", note: "그릇에 먼저 풀어둡니다." },
      { name: "물", display: "3컵", note: "육수가 있으면 더 맛있습니다." },
      { name: "대파", display: "1큰술", prep: "송송 썹니다." },
    ],
  },
  {
    id: "easy-chicken-dumpling-soup",
    name: "닭고기완자국",
    category: "국·찌개",
    method: "끓이기",
    calories: "240",
    cookingTime: 25,
    servings: 2,
    trustLabel: "아이국",
    featuredReason: "다진 닭고기와 두부로 만드는 작고 부드러운 완자국",
    beginnerSummary: "완자는 크게 만들지 않고 숟가락으로 작게 떠 넣으면 익히기 쉽습니다.",
    safetyNote: "완자 속까지 완전히 익었는지 반으로 잘라 확인하세요.",
    imageTone: "작은 닭고기완자와 채소가 담긴 맑은 국",
    ingredients: [
      { name: "닭고기", display: "150g", prep: "다짐육을 씁니다." },
      { name: "두부", display: "1/4모", note: "으깨서 완자를 부드럽게 합니다." },
      { name: "양파", display: "2큰술", prep: "잘게 다집니다." },
      { name: "물", display: "3컵", note: "국물 기준입니다." },
    ],
  },
  {
    id: "easy-mild-kids-curry-rice",
    name: "유아식 카레덮밥 순한맛",
    category: "밥",
    method: "끓이기",
    calories: "420",
    cookingTime: 25,
    servings: 2,
    trustLabel: "아이한그릇",
    featuredReason: "감자와 당근을 푹 익혀 밥에 올리는 순한 카레",
    beginnerSummary: "카레가루는 제품마다 짠맛이 달라서 적게 넣고 농도를 맞춥니다.",
    safetyNote: "어린 아이용은 매운 카레가루를 피하고 향신료 반응을 확인하세요.",
    imageTone: "작게 썬 감자와 당근이 들어간 순한 카레덮밥",
    ingredients: [
      { name: "밥", display: "1공기", note: "따뜻하게 준비합니다." },
      { name: "감자", display: "1개", prep: "작은 큐브로 썹니다." },
      { name: "당근", display: "1/3개", prep: "감자보다 작게 썹니다." },
      { name: "순한 카레가루", display: "1큰술", note: "처음에는 적게 넣습니다." },
    ],
  },
  {
    id: "easy-eomuk-bokkeum",
    name: "어묵볶음",
    category: "반찬",
    method: "볶기",
    calories: "210",
    cookingTime: 12,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "어묵과 양파만 있으면 금방 만드는 기본 밑반찬",
    beginnerSummary: "어묵을 뜨거운 물에 한 번 헹구면 기름기와 짠맛이 조금 줄어듭니다.",
    imageTone: "윤기 있게 볶아진 어묵과 양파 반찬",
    ingredients: [
      { name: "어묵", display: "3장", prep: "한입 크기로 썹니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "간장", display: "1큰술", note: "먼저 절반만 넣습니다." },
      { name: "올리고당", display: "1작은술", note: "윤기를 냅니다." },
    ],
  },
  {
    id: "easy-mild-dubu-jorim",
    name: "두부조림 순한맛",
    category: "반찬",
    method: "조리기",
    calories: "260",
    cookingTime: 18,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "고춧가루 없이 간장으로 조리는 부드러운 두부 반찬",
    beginnerSummary: "두부를 먼저 살짝 구우면 조릴 때 부서지지 않습니다.",
    imageTone: "간장 양념이 자작하게 밴 순한 두부조림",
    ingredients: [
      { name: "두부", display: "1모", prep: "물기를 닦고 큼직하게 썹니다." },
      { name: "간장", display: "2큰술", note: "짜면 물을 더 넣습니다." },
      { name: "대파", display: "2큰술", prep: "송송 썹니다." },
      { name: "물", display: "1/2컵", note: "양념이 타지 않게 합니다." },
    ],
  },
  {
    id: "easy-gyeran-mari-expanded",
    name: "계란말이",
    category: "반찬",
    method: "부치기",
    calories: "260",
    cookingTime: 15,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "도시락과 집밥 모두에 맞는 기본 계란 반찬",
    beginnerSummary: "약불에서 천천히 말면 찢어져도 다음 계란물로 붙일 수 있습니다.",
    safetyNote: "계란은 속까지 촉촉하지만 흐르지 않게 익혀 주세요.",
    imageTone: "노랗게 말린 계란말이가 도톰하게 썰린 모습",
    ingredients: [
      { name: "계란", display: "4개", note: "처음에는 4개가 말기 쉽습니다." },
      { name: "당근", display: "2큰술", prep: "아주 잘게 다집니다." },
      { name: "대파", display: "2큰술", prep: "송송 썹니다." },
      { name: "소금", display: "한꼬집", note: "조금만 넣습니다." },
    ],
  },
  {
    id: "easy-aehobak-jeon",
    name: "애호박전",
    category: "반찬",
    method: "부치기",
    calories: "180",
    cookingTime: 12,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "애호박을 동그랗게 썰어 부치는 가장 쉬운 전",
    beginnerSummary: "애호박은 너무 두껍게 썰지 않아야 속까지 빨리 익습니다.",
    safetyNote: "계란 알레르기가 있으면 달걀물 대신 부침가루 반죽을 쓰세요.",
    imageTone: "동그랗고 노릇한 애호박전 완성 모습",
    ingredients: [
      { name: "애호박", display: "1개", prep: "0.5cm 두께로 썹니다." },
      { name: "계란", display: "1개", note: "달걀물을 입힙니다." },
      { name: "부침가루", display: "3큰술", note: "얇게 묻힙니다." },
      { name: "식용유", display: "1큰술", note: "팬에 얇게 두릅니다." },
    ],
  },
  {
    id: "easy-tuna-jeon",
    name: "참치전",
    category: "반찬",
    method: "부치기",
    calories: "240",
    cookingTime: 13,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "참치캔 하나로 단백질 반찬을 빠르게 만드는 메뉴",
    beginnerSummary: "참치 물기를 빼야 반죽이 질어지지 않습니다.",
    imageTone: "작게 부친 참치전이 노릇하게 쌓인 모습",
    ingredients: [
      { name: "참치", display: "1캔", prep: "기름이나 물을 빼요." },
      { name: "계란", display: "1개", note: "반죽을 묶습니다." },
      { name: "양파", display: "2큰술", prep: "잘게 다집니다." },
      { name: "부침가루", display: "2큰술", note: "질면 조금 더 넣습니다." },
    ],
  },
  {
    id: "easy-egg-fried-rice",
    name: "계란볶음밥",
    category: "밥",
    method: "볶기",
    calories: "410",
    cookingTime: 10,
    servings: 1,
    trustLabel: "초간단 한그릇",
    featuredReason: "밥과 계란만 있어도 바로 만드는 10분 한 끼",
    beginnerSummary: "계란을 먼저 익힌 뒤 밥을 넣으면 비린맛 없이 고슬고슬합니다.",
    safetyNote: "계란은 흐르지 않게 완전히 익힙니다.",
    imageTone: "계란이 고르게 섞인 고슬고슬한 볶음밥",
    ingredients: [
      { name: "밥", display: "1공기", note: "찬밥이면 더 좋습니다." },
      { name: "계란", display: "2개", note: "먼저 스크램블합니다." },
      { name: "대파", display: "2큰술", prep: "송송 썹니다." },
      { name: "간장", display: "1작은술", note: "팬 가장자리에 넣습니다." },
    ],
  },
  {
    id: "easy-tuna-kimchi-fried-rice",
    name: "참치김치볶음밥",
    category: "밥",
    method: "볶기",
    calories: "520",
    cookingTime: 14,
    servings: 1,
    trustLabel: "냉장고파먹기",
    featuredReason: "참치와 김치, 밥으로 끝나는 든든한 한그릇",
    beginnerSummary: "김치를 먼저 충분히 볶으면 신맛이 줄고 밥이 질척하지 않습니다.",
    imageTone: "참치와 김치가 고르게 섞인 붉은 볶음밥",
    ingredients: [
      { name: "밥", display: "1공기", note: "마지막에 넣습니다." },
      { name: "김치", display: "1/2컵", prep: "가위로 잘게 자릅니다." },
      { name: "참치", display: "1/2캔", prep: "기름을 살짝 뺍니다." },
      { name: "참기름", display: "1작은술", note: "불 끄고 넣습니다." },
    ],
  },
  {
    id: "easy-onion-egg-don",
    name: "양파계란덮밥",
    category: "밥",
    method: "덮밥",
    calories: "430",
    cookingTime: 12,
    servings: 1,
    trustLabel: "초간단 한그릇",
    featuredReason: "양파를 달게 익혀 계란으로 덮는 쉬운 덮밥",
    beginnerSummary: "양파가 투명해질 때까지 익히면 설탕 없이도 단맛이 납니다.",
    safetyNote: "계란은 아이용이면 완전히 익혀 주세요.",
    imageTone: "밥 위에 부드러운 양파계란이 덮인 완성 덮밥",
    ingredients: [
      { name: "밥", display: "1공기", note: "그릇에 먼저 담습니다." },
      { name: "양파", display: "1/2개", prep: "얇게 채 썹니다." },
      { name: "계란", display: "2개", note: "마지막에 둘러 익힙니다." },
      { name: "간장", display: "1큰술", note: "물과 섞어 짜지 않게 합니다." },
    ],
  },
  {
    id: "easy-basic-doenjang-jjigae",
    name: "된장찌개 기본형",
    category: "국·찌개",
    method: "끓이기",
    calories: "290",
    cookingTime: 20,
    servings: 2,
    trustLabel: "집밥 기본",
    featuredReason: "두부와 애호박을 소진하기 좋은 가장 익숙한 찌개",
    beginnerSummary: "된장은 처음부터 많이 넣지 말고 마지막에 맛을 보며 조절합니다.",
    imageTone: "두부와 애호박이 보이는 따뜻한 된장찌개",
    ingredients: [
      { name: "된장", display: "2큰술", note: "물에 먼저 풀어 줍니다." },
      { name: "두부", display: "1/2모", prep: "2cm 큐브로 썹니다." },
      { name: "애호박", display: "1/3개", prep: "반달로 썹니다." },
      { name: "양파", display: "1/4개", note: "단맛을 냅니다." },
    ],
  },
  {
    id: "easy-sundubu-egg-soup",
    name: "순두부계란국",
    category: "국·찌개",
    method: "끓이기",
    calories: "190",
    cookingTime: 12,
    servings: 2,
    trustLabel: "쉬운 국",
    featuredReason: "순두부와 계란으로 끓이는 부드러운 단백질 국",
    beginnerSummary: "순두부는 마지막에 넣고 크게 젓지 않아야 모양이 살아 있습니다.",
    safetyNote: "계란은 국물이 다시 끓을 때까지 익힙니다.",
    imageTone: "순두부와 계란이 몽글몽글한 맑은 국",
    ingredients: [
      { name: "순두부", display: "1봉", note: "숟가락으로 크게 떠 넣습니다." },
      { name: "계란", display: "1개", note: "풀어서 마지막에 넣습니다." },
      { name: "물", display: "3컵", note: "육수가 있으면 더 좋습니다." },
      { name: "대파", display: "1큰술", prep: "송송 썹니다." },
    ],
  },
  {
    id: "easy-potato-onion-soup",
    name: "감자양파국",
    category: "국·찌개",
    method: "끓이기",
    calories: "140",
    cookingTime: 15,
    servings: 2,
    trustLabel: "쉬운 국",
    featuredReason: "감자와 양파만으로 맑고 달큰하게 끓이는 국",
    beginnerSummary: "감자를 얇게 썰면 오래 끓이지 않아도 부드럽게 익습니다.",
    imageTone: "감자와 양파가 맑은 국물에 담긴 완성 국",
    ingredients: [
      { name: "감자", display: "1개", prep: "얇게 썹니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "물", display: "3컵", note: "국물 기준입니다." },
      { name: "국간장", display: "1작은술", note: "간은 약하게 합니다." },
    ],
  },
  {
    id: "easy-soy-pork-bulgogi",
    name: "간장돼지불고기",
    category: "일품",
    method: "볶기",
    calories: "460",
    cookingTime: 20,
    servings: 2,
    trustLabel: "쉬운 메인",
    featuredReason: "고추장 없이 간장 양념으로 만드는 순한 돼지고기 볶음",
    beginnerSummary: "고기를 얇게 펴서 볶으면 속까지 빨리 익습니다.",
    safetyNote: "돼지고기는 분홍색이 남지 않게 완전히 익혀야 합니다.",
    imageTone: "간장 양념이 밴 돼지고기와 양파 볶음",
    ingredients: [
      { name: "돼지고기", display: "300g", prep: "불고기용 얇은 고기를 씁니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "간장", display: "2큰술", note: "양념 기준입니다." },
      { name: "설탕", display: "1작은술", note: "단맛을 조금만 냅니다." },
    ],
  },
  {
    id: "easy-pork-mung-sprout-stir-fry",
    name: "돼지고기숙주볶음",
    category: "일품",
    method: "볶기",
    calories: "410",
    cookingTime: 15,
    servings: 2,
    trustLabel: "쉬운 메인",
    featuredReason: "숙주 한 봉지와 돼지고기를 빠르게 볶는 메인 반찬",
    beginnerSummary: "숙주는 오래 볶으면 물이 많이 나오니 마지막에 넣습니다.",
    safetyNote: "돼지고기를 먼저 완전히 익힌 뒤 숙주를 넣습니다.",
    imageTone: "아삭한 숙주와 돼지고기가 함께 볶인 완성 dish",
    ingredients: [
      { name: "돼지고기", display: "250g", prep: "먹기 좋게 자릅니다." },
      { name: "숙주", display: "1봉", prep: "씻어 물기를 뺍니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "간장", display: "1큰술", note: "마지막에 넣습니다." },
    ],
  },
  {
    id: "easy-chicken-teriyaki-don",
    name: "닭고기데리야키덮밥",
    category: "밥",
    method: "덮밥",
    calories: "560",
    cookingTime: 22,
    servings: 2,
    trustLabel: "쉬운 한그릇",
    featuredReason: "닭고기와 양파를 달짝지근하게 조려 밥에 올리는 덮밥",
    beginnerSummary: "닭고기는 한입 크기로 작게 썰어야 속까지 쉽게 익습니다.",
    safetyNote: "닭고기 속이 분홍색이면 더 익혀야 합니다.",
    imageTone: "윤기 나는 닭고기가 밥 위에 올라간 덮밥",
    ingredients: [
      { name: "밥", display: "2공기", note: "그릇에 담아둡니다." },
      { name: "닭고기", display: "250g", prep: "한입 크기로 썹니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "간장", display: "2큰술", note: "물과 섞어 조립니다." },
    ],
  },
  {
    id: "easy-cabbage-egg-jeon",
    name: "양배추계란전",
    category: "반찬",
    method: "부치기",
    calories: "220",
    cookingTime: 15,
    servings: 2,
    trustLabel: "냉장고파먹기",
    featuredReason: "남은 양배추를 계란과 섞어 한 장으로 부치는 메뉴",
    beginnerSummary: "양배추는 얇게 채 썰수록 전이 부드럽고 빨리 익습니다.",
    safetyNote: "계란은 가운데까지 익혀 주세요.",
    imageTone: "양배추가 듬뿍 들어간 도톰한 계란전",
    ingredients: [
      { name: "양배추", display: "2컵", prep: "얇게 채 썹니다." },
      { name: "계란", display: "2개", note: "반죽을 묶어 줍니다." },
      { name: "부침가루", display: "2큰술", note: "없으면 생략 가능합니다." },
      { name: "식용유", display: "1큰술", note: "팬에 얇게 두릅니다." },
    ],
  },
  {
    id: "easy-tomato-egg-stir-fry",
    name: "토마토계란볶음",
    category: "일품",
    method: "볶기",
    calories: "300",
    cookingTime: 12,
    servings: 2,
    trustLabel: "가벼운 한끼",
    featuredReason: "토마토와 계란만으로 만드는 부드러운 볶음",
    beginnerSummary: "계란을 먼저 익혀 덜어두면 토마토 물에 질척해지지 않습니다.",
    safetyNote: "방울토마토를 쓰면 반으로 잘라 주세요.",
    imageTone: "빨간 토마토와 노란 계란이 촉촉하게 볶인 모습",
    ingredients: [
      { name: "토마토", display: "2개", prep: "한입 크기로 썹니다." },
      { name: "계란", display: "3개", note: "먼저 부드럽게 익힙니다." },
      { name: "대파", display: "1큰술", prep: "송송 썹니다." },
      { name: "소금", display: "한꼬집", note: "싱거울 때만 넣습니다." },
    ],
  },
  {
    id: "easy-mushroom-oyster-stir-fry",
    name: "버섯굴소스볶음",
    category: "반찬",
    method: "볶기",
    calories: "150",
    cookingTime: 12,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "버섯 한 팩으로 만드는 감칠맛 반찬",
    beginnerSummary: "버섯은 센불에 짧게 볶아야 물이 덜 생깁니다.",
    imageTone: "윤기 있는 버섯과 양파 볶음 완성 모습",
    ingredients: [
      { name: "버섯", display: "1팩", prep: "먹기 좋게 찢거나 썹니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "굴소스", display: "1큰술", note: "짠맛이 있으니 적게 시작합니다." },
      { name: "식용유", display: "1큰술", note: "팬에 두릅니다." },
    ],
  },
  {
    id: "easy-king-oyster-soy-grill",
    name: "새송이버섯간장구이",
    category: "반찬",
    method: "굽기",
    calories: "120",
    cookingTime: 10,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "새송이버섯을 도톰하게 구워 고기 같은 식감을 내는 반찬",
    beginnerSummary: "버섯에 칼집을 얕게 넣으면 양념이 잘 배고 보기 좋습니다.",
    imageTone: "갈색 간장 윤기가 도는 새송이버섯 구이",
    ingredients: [
      { name: "새송이버섯", display: "2개", prep: "도톰하게 썹니다." },
      { name: "간장", display: "1큰술", note: "물과 섞어 짜지 않게 합니다." },
      { name: "올리고당", display: "1작은술", note: "윤기를 냅니다." },
      { name: "식용유", display: "1작은술", note: "팬에 얇게 두릅니다." },
    ],
  },
  {
    id: "easy-eggplant-bokkeum",
    name: "가지볶음",
    category: "반찬",
    method: "볶기",
    calories: "130",
    cookingTime: 12,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "가지와 양파를 간장으로 부드럽게 볶는 밑반찬",
    beginnerSummary: "가지는 기름을 많이 먹으니 물을 조금 넣어 촉촉하게 익힙니다.",
    imageTone: "부드럽게 익은 보라색 가지볶음 완성 모습",
    ingredients: [
      { name: "가지", display: "2개", prep: "반달로 썹니다." },
      { name: "양파", display: "1/2개", prep: "채 썹니다." },
      { name: "간장", display: "1큰술", note: "마지막에 넣습니다." },
      { name: "물", display: "2큰술", note: "촉촉하게 익힙니다." },
    ],
  },
  {
    id: "easy-lotus-root-jorim",
    name: "연근조림",
    category: "반찬",
    method: "조리기",
    calories: "180",
    cookingTime: 25,
    servings: 3,
    trustLabel: "밑반찬",
    featuredReason: "얇게 썬 연근을 달짝지근하게 조리는 저장 반찬",
    beginnerSummary: "연근은 얇게 썰어야 딱딱하지 않고 양념도 잘 배어듭니다.",
    safetyNote: "아이용은 충분히 익혀 아삭함보다 부드러움을 우선합니다.",
    imageTone: "갈색 양념이 밴 얇은 연근조림 완성 모습",
    ingredients: [
      { name: "연근", display: "250g", prep: "얇게 썰어 식초물에 담급니다." },
      { name: "간장", display: "2큰술", note: "물과 함께 조립니다." },
      { name: "물", display: "1컵", note: "연근을 부드럽게 익힙니다." },
      { name: "올리고당", display: "1큰술", note: "마지막 윤기용입니다." },
    ],
  },
  {
    id: "easy-radish-jorim",
    name: "무조림",
    category: "반찬",
    method: "조리기",
    calories: "110",
    cookingTime: 25,
    servings: 2,
    trustLabel: "쉬운 반찬",
    featuredReason: "무를 푹 익혀 밥에 올려 먹기 좋은 부드러운 조림",
    beginnerSummary: "무는 작게 썰수록 빨리 익고 양념이 잘 배어듭니다.",
    imageTone: "양념이 밴 부드러운 무조림 완성 모습",
    ingredients: [
      { name: "무", display: "2컵", prep: "두껍지 않게 썹니다." },
      { name: "간장", display: "1큰술", note: "짜지 않게 시작합니다." },
      { name: "물", display: "1컵", note: "무를 푹 익힙니다." },
      { name: "대파", display: "1큰술", prep: "마지막에 넣습니다." },
    ],
  },
  {
    id: "easy-samchi-soy-grill",
    name: "삼치간장구이",
    category: "일품",
    method: "굽기",
    calories: "330",
    cookingTime: 18,
    servings: 2,
    trustLabel: "생선 반찬",
    featuredReason: "삼치를 간장 양념으로 순하게 굽는 생선 메뉴",
    beginnerSummary: "생선은 물기를 닦아야 팬에서 덜 튀고 겉이 잘 익습니다.",
    safetyNote: "아이에게 줄 때는 가시를 한 번 더 확인합니다.",
    imageTone: "노릇하게 구운 삼치에 연한 간장 소스가 올라간 모습",
    ingredients: [
      { name: "삼치", display: "2토막", prep: "물기를 닦고 가시를 확인합니다." },
      { name: "간장", display: "1큰술", note: "양념 기준입니다." },
      { name: "맛술", display: "1큰술", note: "비린 향을 줄입니다." },
      { name: "식용유", display: "1큰술", note: "팬에 두릅니다." },
    ],
  },
  {
    id: "easy-basic-curry-rice",
    name: "카레라이스 기본형",
    category: "밥",
    method: "끓이기",
    calories: "560",
    cookingTime: 30,
    servings: 3,
    trustLabel: "쉬운 한그릇",
    featuredReason: "감자, 당근, 양파를 한 냄비에 넣고 끓이는 기본 카레",
    beginnerSummary: "딱딱한 채소부터 충분히 익힌 뒤 카레가루를 넣어야 덩어리가 적습니다.",
    imageTone: "감자와 당근이 들어간 노란 카레라이스 완성 모습",
    ingredients: [
      { name: "밥", display: "3공기", note: "인원수만큼 준비합니다." },
      { name: "감자", display: "2개", prep: "작은 큐브로 썹니다." },
      { name: "당근", display: "1개", prep: "감자보다 작게 썹니다." },
      { name: "카레가루", display: "4큰술", note: "물에 풀어 넣으면 덜 뭉칩니다." },
    ],
  },
  {
    id: "easy-janchi-guksu",
    name: "잔치국수",
    category: "분식",
    method: "끓이기",
    calories: "430",
    cookingTime: 25,
    servings: 2,
    trustLabel: "쉬운 면요리",
    featuredReason: "소면과 계란, 애호박으로 만드는 따뜻한 국수",
    beginnerSummary: "소면은 삶은 뒤 찬물에 비벼 씻어야 면이 덜 불고 깔끔합니다.",
    safetyNote: "어린 아이에게는 면을 가위로 짧게 잘라 주세요.",
    imageTone: "애호박 고명과 계란 지단이 올라간 잔치국수",
    ingredients: [
      { name: "소면", display: "2인분", prep: "끓는 물에 삶습니다." },
      { name: "계란", display: "1개", note: "지단이나 풀어 넣기로 준비합니다." },
      { name: "애호박", display: "1/3개", prep: "채 썰어 볶습니다." },
      { name: "육수", display: "3컵", note: "멸치육수나 코인육수를 씁니다." },
    ],
  },
];

export const EASY_RECIPE_EXPANSION: CuratedRecipe[] = EASY_RECIPE_SPECS.map(makeRecipe);
