insert into public.ingredients_catalog (
  id, canonical_name, category, default_storage_type, common_unit, allergen_group
) values
  ('veg-onion', '양파', '채소', '냉장', 'piece', null),
  ('veg-green-onion', '대파', '채소', '냉장', 'piece', null),
  ('veg-garlic', '마늘', '채소', '냉장', 'g', null),
  ('veg-potato', '감자', '채소', '실온', 'piece', null),
  ('veg-sweet-potato', '고구마', '채소', '실온', 'piece', null),
  ('veg-carrot', '당근', '채소', '냉장', 'piece', null),
  ('veg-zucchini', '애호박', '채소', '냉장', 'piece', null),
  ('veg-cucumber', '오이', '채소', '냉장', 'piece', null),
  ('veg-cabbage', '양배추', '채소', '냉장', 'piece', null),
  ('veg-kimchi-cabbage', '배추', '채소', '냉장', 'piece', null),
  ('veg-radish', '무', '채소', '냉장', 'piece', null),
  ('veg-broccoli', '브로콜리', '채소', '냉장', 'piece', null),
  ('veg-mushroom', '버섯', '채소', '냉장', 'pack', null),
  ('veg-spinach', '시금치', '채소', '냉장', 'bag', null),
  ('veg-paprika', '파프리카', '채소', '냉장', 'piece', null),
  ('veg-lettuce', '상추', '채소', '냉장', 'bag', null),
  ('veg-perilla-leaf', '깻잎', '채소', '냉장', 'pack', null),
  ('veg-bean-sprout', '콩나물', '채소', '냉장', 'bag', null),
  ('veg-sprout', '숙주', '채소', '냉장', 'bag', null),
  ('veg-tomato-cherry', '방울토마토', '채소', '냉장', 'pack', null),
  ('fruit-apple', '사과', '과일', '실온', 'piece', null),
  ('fruit-pear', '배', '과일', '실온', 'piece', null),
  ('fruit-banana', '바나나', '과일', '실온', 'piece', null),
  ('fruit-strawberry', '딸기', '과일', '냉장', 'pack', null),
  ('fruit-orange', '오렌지', '과일', '실온', 'piece', null),
  ('fruit-tangerine', '귤', '과일', '실온', 'piece', null),
  ('fruit-lemon', '레몬', '과일', '냉장', 'piece', null),
  ('fruit-lime', '라임', '과일', '냉장', 'piece', null),
  ('fruit-grape', '포도', '과일', '냉장', 'pack', null),
  ('fruit-blueberry', '블루베리', '과일', '냉장', 'pack', null),
  ('fruit-kiwi', '키위', '과일', '실온', 'piece', null),
  ('fruit-mango', '망고', '과일', '실온', 'piece', null),
  ('fruit-pineapple', '파인애플', '과일', '실온', 'piece', null),
  ('fruit-avocado', '아보카도', '과일', '실온', 'piece', null),
  ('meat-beef', '소고기', '육류', '냉장', 'g', null),
  ('meat-pork', '돼지고기', '육류', '냉장', 'g', null),
  ('meat-pork-belly', '삼겹살', '육류', '냉장', 'g', null),
  ('meat-pork-neck', '목살', '육류', '냉장', 'g', null),
  ('meat-beef-bulgogi', '불고기용 소고기', '육류', '냉장', 'g', null),
  ('meat-chicken', '닭고기', '육류', '냉장', 'g', null),
  ('meat-chicken-breast', '닭가슴살', '육류', '냉장', 'pack', null),
  ('meat-chicken-leg', '닭다리', '육류', '냉장', 'piece', null),
  ('meat-duck', '오리고기', '육류', '냉장', 'g', null),
  ('meat-bacon', '베이컨', '육류', '냉장', 'pack', null),
  ('meat-ham', '햄', '육류', '냉장', 'pack', null),
  ('meat-sausage', '소시지', '육류', '냉장', 'pack', null),
  ('sea-mackerel', '고등어', '수산물', '냉장', 'piece', null),
  ('sea-salmon', '연어', '수산물', '냉장', 'g', null),
  ('sea-tuna', '참치', '수산물', '냉장', 'g', null),
  ('sea-shrimp', '새우', '수산물', '냉장', 'g', null),
  ('sea-squid', '오징어', '수산물', '냉장', 'piece', null),
  ('sea-octopus', '문어', '수산물', '냉장', 'piece', null),
  ('sea-anchovy', '멸치', '수산물', '실온', 'g', null),
  ('sea-kelp', '다시마', '수산물', '실온', 'sheet', null),
  ('sea-seaweed', '미역', '수산물', '실온', 'g', null),
  ('sea-clam', '바지락', '수산물', '냉장', 'pack', null),
  ('sea-pollack-roe', '명란', '수산물', '냉장', 'pack', null),
  ('sea-fishcake', '어묵', '수산물', '냉장', 'pack', null),
  ('dairy-milk', '우유', '유제품', '냉장', 'ml', null),
  ('dairy-soy-milk', '두유', '유제품', '냉장', 'ml', null),
  ('dairy-cheese', '치즈', '유제품', '냉장', 'pack', null),
  ('dairy-mozzarella', '모짜렐라치즈', '유제품', '냉장', 'pack', null),
  ('dairy-butter', '버터', '유제품', '냉장', 'g', null),
  ('dairy-yogurt', '요거트', '유제품', '냉장', 'cup', null),
  ('dairy-whipping-cream', '생크림', '유제품', '냉장', 'ml', null),
  ('dairy-egg', '계란', '유제품', '냉장', 'piece', null),
  ('dairy-tofu', '두부', '유제품', '냉장', 'block', null),
  ('dairy-cream-cheese', '크림치즈', '유제품', '냉장', 'g', null),
  ('dairy-mayonnaise', '마요네즈', '유제품', '냉장', 'g', null),
  ('dairy-parmesan', '파마산치즈', '유제품', '냉장', 'g', null),
  ('frozen-dumpling', '냉동만두', '냉동식품', '냉동', 'bag', null),
  ('frozen-rice', '냉동볶음밥', '냉동식품', '냉동', 'pack', null),
  ('frozen-pizza', '냉동피자', '냉동식품', '냉동', 'piece', null),
  ('frozen-udon', '냉동우동면', '냉동식품', '냉동', 'pack', null),
  ('frozen-shrimp', '냉동새우', '냉동식품', '냉동', 'bag', null),
  ('frozen-squid', '냉동오징어', '냉동식품', '냉동', 'bag', null),
  ('frozen-chicken', '냉동닭가슴살', '냉동식품', '냉동', 'pack', null),
  ('frozen-pork-cutlet', '냉동돈까스', '냉동식품', '냉동', 'pack', null),
  ('frozen-fishcake', '냉동어묵', '냉동식품', '냉동', 'pack', null),
  ('frozen-vegetable-mix', '냉동야채믹스', '냉동식품', '냉동', 'bag', null),
  ('frozen-blueberry', '냉동블루베리', '냉동식품', '냉동', 'bag', null),
  ('frozen-fries', '냉동감자튀김', '냉동식품', '냉동', 'bag', null),
  ('season-soy-soup', '국간장', '조미료', '실온', 'tbsp', null),
  ('season-soy-dark', '진간장', '조미료', '실온', 'tbsp', null),
  ('season-gochujang', '고추장', '조미료', '실온', 'tbsp', null),
  ('season-doenjang', '된장', '조미료', '실온', 'tbsp', null),
  ('season-ssamjang', '쌈장', '조미료', '실온', 'tbsp', null),
  ('season-salt', '소금', '조미료', '실온', 'tsp', null),
  ('season-sugar', '설탕', '조미료', '실온', 'tbsp', null),
  ('season-vinegar', '식초', '조미료', '실온', 'tbsp', null),
  ('season-sesame-oil', '참기름', '조미료', '실온', 'tbsp', null),
  ('season-perilla-oil', '들기름', '조미료', '실온', 'tbsp', null),
  ('season-pepper', '후추', '조미료', '실온', 'tsp', null),
  ('season-pepper-powder', '고춧가루', '조미료', '실온', 'tbsp', null),
  ('season-oyster-sauce', '굴소스', '조미료', '실온', 'tbsp', null),
  ('season-curry', '카레가루', '조미료', '실온', 'tbsp', null),
  ('season-ketchup', '케첩', '조미료', '실온', 'tbsp', null),
  ('grain-rice', '쌀', '곡물/면/빵', '실온', 'kg', null),
  ('grain-brown-rice', '현미', '곡물/면/빵', '실온', 'kg', null),
  ('grain-flour', '밀가루', '곡물/면/빵', '실온', 'g', null),
  ('grain-starch', '전분', '곡물/면/빵', '실온', 'g', null),
  ('grain-noodle', '국수', '곡물/면/빵', '실온', 'g', null),
  ('grain-ramen', '라면', '곡물/면/빵', '실온', 'pack', null),
  ('grain-pasta', '파스타면', '곡물/면/빵', '실온', 'g', null),
  ('grain-udon', '우동면', '곡물/면/빵', '냉장', 'pack', null),
  ('grain-bread', '식빵', '곡물/면/빵', '실온', 'slice', null),
  ('grain-baguette', '바게트', '곡물/면/빵', '실온', 'piece', null),
  ('grain-breadcrumb', '빵가루', '곡물/면/빵', '실온', 'g', null),
  ('grain-ricecake', '떡', '곡물/면/빵', '냉장', 'pack', null),
  ('proc-tuna-can', '참치캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-corn-can', '옥수수캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-beans-can', '콩통조림', '통조림/가공식품', '실온', 'can', null),
  ('proc-spam', '스팸', '통조림/가공식품', '실온', 'can', null),
  ('proc-kimchi', '김치', '통조림/가공식품', '냉장', 'pack', null),
  ('proc-pickle', '피클', '통조림/가공식품', '냉장', 'bottle', null),
  ('proc-olive', '올리브', '통조림/가공식품', '냉장', 'bottle', null),
  ('proc-jam', '잼', '통조림/가공식품', '냉장', 'bottle', null),
  ('proc-sauce-pasta', '토마토소스', '통조림/가공식품', '실온', 'bottle', null),
  ('proc-stock', '육수팩', '통조림/가공식품', '실온', 'pack', null),
  ('misc-water', '생수', '음료/기타', '실온', 'bottle', null),
  ('misc-sparkling-water', '탄산수', '음료/기타', '실온', 'bottle', null),
  ('misc-orange-juice', '오렌지주스', '음료/기타', '냉장', 'ml', null),
  ('misc-apple-juice', '사과주스', '음료/기타', '냉장', 'ml', null),
  ('misc-coffee', '커피', '음료/기타', '실온', 'g', null),
  ('misc-tea', '티백', '음료/기타', '실온', 'pack', null),
  ('misc-nuts', '견과류', '음료/기타', '실온', 'bag', null),
  ('misc-honey', '꿀', '음료/기타', '실온', 'tbsp', null),
  ('misc-syrup', '올리고당', '음료/기타', '실온', 'tbsp', null),
  ('misc-cocoa', '코코아가루', '음료/기타', '실온', 'tbsp', null),
  ('veg-chili-pepper', '고추', '채소', '냉장', 'piece', null),
  ('veg-eggplant', '가지', '채소', '냉장', 'piece', null),
  ('veg-garlic-chive', '부추', '채소', '냉장', 'bag', null),
  ('veg-minari', '미나리', '채소', '냉장', 'bag', null),
  ('veg-bok-choy', '청경채', '채소', '냉장', 'bag', null),
  ('veg-young-napa', '알배추', '채소', '냉장', 'piece', null),
  ('veg-pumpkin-sweet', '단호박', '채소', '실온', 'piece', null),
  ('veg-lotus-root', '연근', '채소', '냉장', 'g', null),
  ('veg-burdock', '우엉', '채소', '냉장', 'g', null),
  ('veg-bracken', '고사리', '채소', '냉장', 'pack', null),
  ('veg-balloon-flower-root', '도라지', '채소', '냉장', 'pack', null),
  ('veg-chives', '실파', '채소', '냉장', 'bag', null),
  ('meat-ground-pork', '다진 돼지고기', '육류', '냉장', 'g', null),
  ('meat-ground-beef', '다진 소고기', '육류', '냉장', 'g', null),
  ('meat-chicken-tenderloin', '닭안심', '육류', '냉장', 'g', null),
  ('meat-pork-rib', '돼지갈비', '육류', '냉장', 'g', null),
  ('sea-hairtail', '갈치', '수산물', '냉장', 'piece', null),
  ('sea-cod', '대구', '수산물', '냉장', 'piece', null),
  ('sea-pollack', '동태', '수산물', '냉동', 'piece', null),
  ('sea-dried-pollack', '황태채', '수산물', '실온', 'g', null),
  ('frozen-tteokbokki', '냉동떡볶이', '냉동식품', '냉동', 'pack', null),
  ('frozen-hotdog', '냉동핫도그', '냉동식품', '냉동', 'pack', null),
  ('frozen-corn', '냉동옥수수', '냉동식품', '냉동', 'bag', null),
  ('frozen-spinach', '냉동시금치', '냉동식품', '냉동', 'bag', null),
  ('season-cooking-wine', '맛술', '조미료', '실온', 'tbsp', null),
  ('season-fish-sauce-anchovy', '멸치액젓', '조미료', '실온', 'tbsp', null),
  ('season-fish-sauce-sandlance', '까나리액젓', '조미료', '실온', 'tbsp', null),
  ('season-chicken-stock', '치킨스톡', '조미료', '실온', 'tbsp', null),
  ('season-sesame-seed', '깨', '조미료', '실온', 'tsp', null),
  ('season-perilla-powder', '들깨가루', '조미료', '실온', 'tbsp', null),
  ('season-chili-oil', '고추기름', '조미료', '실온', 'tbsp', null),
  ('season-mustard', '겨자', '조미료', '냉장', 'tsp', null),
  ('season-plum-syrup', '매실청', '조미료', '실온', 'tbsp', null),
  ('grain-glass-noodle', '당면', '곡물/면/빵', '실온', 'g', null),
  ('grain-somen', '소면', '곡물/면/빵', '실온', 'g', null),
  ('grain-ramyeon-noodle', '라면사리', '곡물/면/빵', '실온', 'pack', null),
  ('grain-tortilla', '또띠아', '곡물/면/빵', '냉장', 'pack', null),
  ('grain-rice-paper', '라이스페이퍼', '곡물/면/빵', '실온', 'pack', null),
  ('grain-oatmeal', '오트밀', '곡물/면/빵', '실온', 'g', null),
  ('proc-tomato-can', '토마토캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-whelk-can', '골뱅이캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-pacific-saury-can', '꽁치캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-mackerel-can', '고등어캔', '통조림/가공식품', '실온', 'can', null),
  ('proc-chicken-breast-can', '닭가슴살캔', '통조림/가공식품', '실온', 'can', null)
on conflict (id) do update
set canonical_name = excluded.canonical_name,
    category = excluded.category,
    default_storage_type = excluded.default_storage_type,
    common_unit = excluded.common_unit,
    allergen_group = excluded.allergen_group,
    active = true,
    updated_at = now();

insert into public.ingredient_aliases (
  ingredient_id, alias, normalized_alias, alias_type, locale
) values
  ('veg-eggplant', '가지', '가지', 'canonical', 'ko-KR'),
  ('season-soy-dark', '간장', '간장', 'synonym', 'ko-KR'),
  ('season-sugar', '갈색설탕', '갈색설탕', 'synonym', 'ko-KR'),
  ('sea-hairtail', '갈치', '갈치', 'canonical', 'ko-KR'),
  ('veg-potato', '감자', '감자', 'canonical', 'ko-KR'),
  ('grain-starch', '감자전분', '감자전분', 'synonym', 'ko-KR'),
  ('proc-beans-can', '강낭콩', '강낭콩', 'synonym', 'ko-KR'),
  ('season-mustard', '겨자', '겨자', 'canonical', 'ko-KR'),
  ('misc-nuts', '견과류', '견과류', 'canonical', 'ko-KR'),
  ('dairy-egg', '계란', '계란', 'canonical', 'ko-KR'),
  ('veg-sweet-potato', '고구마', '고구마', 'canonical', 'ko-KR'),
  ('sea-mackerel', '고등어', '고등어', 'canonical', 'ko-KR'),
  ('proc-mackerel-can', '고등어캔', '고등어캔', 'canonical', 'ko-KR'),
  ('proc-mackerel-can', '고등어 통조림', '고등어통조림', 'synonym', 'ko-KR'),
  ('veg-bracken', '고사리', '고사리', 'canonical', 'ko-KR'),
  ('veg-chili-pepper', '고추', '고추', 'canonical', 'ko-KR'),
  ('season-chili-oil', '고추기름', '고추기름', 'canonical', 'ko-KR'),
  ('season-gochujang', '고추장', '고추장', 'canonical', 'ko-KR'),
  ('season-pepper-powder', '고춧가루', '고춧가루', 'canonical', 'ko-KR'),
  ('proc-whelk-can', '골뱅이캔', '골뱅이캔', 'canonical', 'ko-KR'),
  ('proc-whelk-can', '골뱅이 통조림', '골뱅이통조림', 'synonym', 'ko-KR'),
  ('season-soy-soup', '국간장', '국간장', 'canonical', 'ko-KR'),
  ('meat-beef', '국거리', '국거리', 'synonym', 'ko-KR'),
  ('sea-anchovy', '국물멸치', '국물멸치', 'synonym', 'ko-KR'),
  ('grain-noodle', '국수', '국수', 'canonical', 'ko-KR'),
  ('season-oyster-sauce', '굴소스', '굴소스', 'canonical', 'ko-KR'),
  ('season-salt', '굵은소금', '굵은소금', 'synonym', 'ko-KR'),
  ('veg-green-onion', '굵은파', '굵은파', 'synonym', 'ko-KR'),
  ('fruit-tangerine', '귤', '귤', 'canonical', 'ko-KR'),
  ('proc-kimchi', '김치', '김치', 'canonical', 'ko-KR'),
  ('season-fish-sauce-sandlance', '까나리액젓', '까나리액젓', 'canonical', 'ko-KR'),
  ('veg-garlic', '깐마늘', '깐마늘', 'synonym', 'ko-KR'),
  ('season-sesame-seed', '깨', '깨', 'canonical', 'ko-KR'),
  ('veg-perilla-leaf', '깻잎', '깻잎', 'canonical', 'ko-KR'),
  ('proc-pacific-saury-can', '꽁치캔', '꽁치캔', 'canonical', 'ko-KR'),
  ('proc-pacific-saury-can', '꽁치 통조림', '꽁치통조림', 'synonym', 'ko-KR'),
  ('season-salt', '꽃소금', '꽃소금', 'synonym', 'ko-KR'),
  ('misc-honey', '꿀', '꿀', 'canonical', 'ko-KR'),
  ('frozen-fries', '냉동감자튀김', '냉동감자튀김', 'canonical', 'ko-KR'),
  ('frozen-chicken', '냉동닭가슴살', '냉동닭가슴살', 'canonical', 'ko-KR'),
  ('frozen-pork-cutlet', '냉동돈까스', '냉동돈까스', 'canonical', 'ko-KR'),
  ('frozen-tteokbokki', '냉동떡볶이', '냉동떡볶이', 'canonical', 'ko-KR'),
  ('frozen-dumpling', '냉동만두', '냉동만두', 'canonical', 'ko-KR'),
  ('frozen-rice', '냉동볶음밥', '냉동볶음밥', 'canonical', 'ko-KR'),
  ('frozen-blueberry', '냉동블루베리', '냉동블루베리', 'canonical', 'ko-KR'),
  ('frozen-shrimp', '냉동새우', '냉동새우', 'canonical', 'ko-KR'),
  ('frozen-spinach', '냉동시금치', '냉동시금치', 'canonical', 'ko-KR'),
  ('frozen-vegetable-mix', '냉동야채믹스', '냉동야채믹스', 'canonical', 'ko-KR'),
  ('frozen-fishcake', '냉동어묵', '냉동어묵', 'canonical', 'ko-KR'),
  ('frozen-squid', '냉동오징어', '냉동오징어', 'canonical', 'ko-KR'),
  ('frozen-corn', '냉동옥수수', '냉동옥수수', 'canonical', 'ko-KR'),
  ('frozen-udon', '냉동우동면', '냉동우동면', 'canonical', 'ko-KR'),
  ('frozen-pizza', '냉동피자', '냉동피자', 'canonical', 'ko-KR'),
  ('frozen-hotdog', '냉동핫도그', '냉동핫도그', 'canonical', 'ko-KR'),
  ('veg-paprika', '노랑 파프리카', '노랑파프리카', 'synonym', 'ko-KR'),
  ('misc-tea', '녹차', '녹차', 'synonym', 'ko-KR'),
  ('veg-mushroom', '느타리버섯', '느타리버섯', 'synonym', 'ko-KR'),
  ('sea-kelp', '다시마', '다시마', 'canonical', 'ko-KR'),
  ('meat-ground-pork', '다진 돼지고기', '다진돼지고기', 'canonical', 'ko-KR'),
  ('meat-ground-beef', '다진 소고기', '다진소고기', 'canonical', 'ko-KR'),
  ('veg-pumpkin-sweet', '단호박', '단호박', 'canonical', 'ko-KR'),
  ('dairy-egg', '달걀', '달걀', 'synonym', 'ko-KR'),
  ('meat-chicken-breast', '닭가슴살', '닭가슴살', 'canonical', 'ko-KR'),
  ('proc-chicken-breast-can', '닭가슴살캔', '닭가슴살캔', 'canonical', 'ko-KR'),
  ('meat-chicken', '닭고기', '닭고기', 'canonical', 'ko-KR'),
  ('meat-chicken-leg', '닭다리', '닭다리', 'canonical', 'ko-KR'),
  ('meat-chicken-tenderloin', '닭안심', '닭안심', 'canonical', 'ko-KR'),
  ('season-chicken-stock', '닭육수', '닭육수', 'synonym', 'ko-KR'),
  ('meat-chicken', '닭정육', '닭정육', 'synonym', 'ko-KR'),
  ('veg-carrot', '당근', '당근', 'canonical', 'ko-KR'),
  ('grain-glass-noodle', '당면', '당면', 'canonical', 'ko-KR'),
  ('sea-cod', '대구', '대구', 'canonical', 'ko-KR'),
  ('veg-green-onion', '대파', '대파', 'canonical', 'ko-KR'),
  ('veg-balloon-flower-root', '도라지', '도라지', 'canonical', 'ko-KR'),
  ('sea-pollack', '동태', '동태', 'canonical', 'ko-KR'),
  ('meat-pork-rib', '돼지갈비', '돼지갈비', 'canonical', 'ko-KR'),
  ('meat-pork', '돼지고기', '돼지고기', 'canonical', 'ko-KR'),
  ('meat-ground-pork', '돼지고기 다짐육', '돼지고기다짐육', 'synonym', 'ko-KR'),
  ('season-doenjang', '된장', '된장', 'canonical', 'ko-KR'),
  ('dairy-tofu', '두부', '두부', 'canonical', 'ko-KR'),
  ('dairy-soy-milk', '두유', '두유', 'canonical', 'ko-KR'),
  ('meat-pork', '뒷다리살', '뒷다리살', 'synonym', 'ko-KR'),
  ('season-perilla-oil', '들기름', '들기름', 'canonical', 'ko-KR'),
  ('season-perilla-powder', '들깨가루', '들깨가루', 'canonical', 'ko-KR'),
  ('fruit-strawberry', '딸기', '딸기', 'canonical', 'ko-KR'),
  ('proc-jam', '딸기잼', '딸기잼', 'synonym', 'ko-KR'),
  ('grain-ricecake', '떡', '떡', 'canonical', 'ko-KR'),
  ('grain-ricecake', '떡국떡', '떡국떡', 'synonym', 'ko-KR'),
  ('grain-ricecake', '떡볶이떡', '떡볶이떡', 'synonym', 'ko-KR'),
  ('grain-tortilla', '또띠아', '또띠아', 'canonical', 'ko-KR'),
  ('grain-ramen', '라면', '라면', 'canonical', 'ko-KR'),
  ('grain-ramyeon-noodle', '라면사리', '라면사리', 'canonical', 'ko-KR'),
  ('grain-rice-paper', '라이스페이퍼', '라이스페이퍼', 'canonical', 'ko-KR'),
  ('fruit-lime', '라임', '라임', 'canonical', 'ko-KR'),
  ('fruit-lemon', '레몬', '레몬', 'canonical', 'ko-KR'),
  ('veg-garlic', '마늘', '마늘', 'canonical', 'ko-KR'),
  ('dairy-mayonnaise', '마요네즈', '마요네즈', 'canonical', 'ko-KR'),
  ('season-cooking-wine', '맛술', '맛술', 'canonical', 'ko-KR'),
  ('fruit-mango', '망고', '망고', 'canonical', 'ko-KR'),
  ('season-plum-syrup', '매실청', '매실청', 'canonical', 'ko-KR'),
  ('sea-anchovy', '멸치', '멸치', 'canonical', 'ko-KR'),
  ('season-fish-sauce-anchovy', '멸치액젓', '멸치액젓', 'canonical', 'ko-KR'),
  ('proc-stock', '멸치육수팩', '멸치육수팩', 'synonym', 'ko-KR'),
  ('sea-pollack-roe', '명란', '명란', 'canonical', 'ko-KR'),
  ('sea-pollack-roe', '명란젓', '명란젓', 'synonym', 'ko-KR'),
  ('sea-pollack', '명태', '명태', 'synonym', 'ko-KR'),
  ('dairy-mozzarella', '모짜렐라', '모짜렐라', 'synonym', 'ko-KR'),
  ('dairy-mozzarella', '모짜렐라치즈', '모짜렐라치즈', 'canonical', 'ko-KR'),
  ('meat-pork-neck', '목살', '목살', 'canonical', 'ko-KR'),
  ('veg-radish', '무', '무', 'canonical', 'ko-KR'),
  ('sea-octopus', '문어', '문어', 'canonical', 'ko-KR'),
  ('veg-minari', '미나리', '미나리', 'canonical', 'ko-KR'),
  ('season-cooking-wine', '미림', '미림', 'synonym', 'ko-KR'),
  ('sea-seaweed', '미역', '미역', 'canonical', 'ko-KR'),
  ('grain-flour', '밀가루', '밀가루', 'canonical', 'ko-KR'),
  ('grain-baguette', '바게트', '바게트', 'canonical', 'ko-KR'),
  ('fruit-banana', '바나나', '바나나', 'canonical', 'ko-KR'),
  ('sea-clam', '바지락', '바지락', 'canonical', 'ko-KR'),
  ('veg-sweet-potato', '밤고구마', '밤고구마', 'synonym', 'ko-KR'),
  ('veg-tomato-cherry', '방울토마토', '방울토마토', 'canonical', 'ko-KR'),
  ('fruit-pear', '배', '배', 'canonical', 'ko-KR'),
  ('veg-kimchi-cabbage', '배추', '배추', 'canonical', 'ko-KR'),
  ('proc-kimchi', '배추김치', '배추김치', 'synonym', 'ko-KR'),
  ('season-sugar', '백설탕', '백설탕', 'synonym', 'ko-KR'),
  ('veg-mushroom', '버섯', '버섯', 'canonical', 'ko-KR'),
  ('dairy-butter', '버터', '버터', 'canonical', 'ko-KR'),
  ('meat-bacon', '베이컨', '베이컨', 'canonical', 'ko-KR'),
  ('proc-beans-can', '병아리콩', '병아리콩', 'synonym', 'ko-KR'),
  ('veg-garlic-chive', '부추', '부추', 'canonical', 'ko-KR'),
  ('sea-dried-pollack', '북어채', '북어채', 'synonym', 'ko-KR'),
  ('meat-beef-bulgogi', '불고기', '불고기', 'synonym', 'ko-KR'),
  ('meat-beef-bulgogi', '불고기용 소고기', '불고기용소고기', 'canonical', 'ko-KR'),
  ('veg-broccoli', '브로콜리', '브로콜리', 'canonical', 'ko-KR'),
  ('fruit-blueberry', '블루베리', '블루베리', 'canonical', 'ko-KR'),
  ('proc-jam', '블루베리잼', '블루베리잼', 'synonym', 'ko-KR'),
  ('meat-sausage', '비엔나', '비엔나', 'synonym', 'ko-KR'),
  ('veg-paprika', '빨강 파프리카', '빨강파프리카', 'synonym', 'ko-KR'),
  ('grain-breadcrumb', '빵가루', '빵가루', 'canonical', 'ko-KR'),
  ('fruit-apple', '사과', '사과', 'canonical', 'ko-KR'),
  ('misc-apple-juice', '사과주스', '사과주스', 'canonical', 'ko-KR'),
  ('veg-bracken', '삶은고사리', '삶은고사리', 'synonym', 'ko-KR'),
  ('meat-pork-belly', '삼겹살', '삼겹살', 'canonical', 'ko-KR'),
  ('veg-lettuce', '상추', '상추', 'canonical', 'ko-KR'),
  ('sea-shrimp', '새우', '새우', 'canonical', 'ko-KR'),
  ('misc-water', '생수', '생수', 'canonical', 'ko-KR'),
  ('sea-tuna', '생참치', '생참치', 'synonym', 'ko-KR'),
  ('dairy-whipping-cream', '생크림', '생크림', 'canonical', 'ko-KR'),
  ('season-sugar', '설탕', '설탕', 'canonical', 'ko-KR'),
  ('meat-beef', '소고기', '소고기', 'canonical', 'ko-KR'),
  ('meat-ground-beef', '소고기 다짐육', '소고기다짐육', 'synonym', 'ko-KR'),
  ('season-salt', '소금', '소금', 'canonical', 'ko-KR'),
  ('grain-somen', '소면', '소면', 'canonical', 'ko-KR'),
  ('meat-sausage', '소시지', '소시지', 'canonical', 'ko-KR'),
  ('veg-potato', '수미감자', '수미감자', 'synonym', 'ko-KR'),
  ('veg-sprout', '숙주', '숙주', 'canonical', 'ko-KR'),
  ('veg-sprout', '숙주나물', '숙주나물', 'synonym', 'ko-KR'),
  ('grain-pasta', '스파게티면', '스파게티면', 'synonym', 'ko-KR'),
  ('proc-spam', '스팸', '스팸', 'canonical', 'ko-KR'),
  ('dairy-cheese', '슬라이스치즈', '슬라이스치즈', 'synonym', 'ko-KR'),
  ('meat-ham', '슬라이스햄', '슬라이스햄', 'synonym', 'ko-KR'),
  ('veg-spinach', '시금치', '시금치', 'canonical', 'ko-KR'),
  ('grain-bread', '식빵', '식빵', 'canonical', 'ko-KR'),
  ('season-vinegar', '식초', '식초', 'canonical', 'ko-KR'),
  ('fruit-pear', '신고배', '신고배', 'synonym', 'ko-KR'),
  ('veg-chives', '실파', '실파', 'canonical', 'ko-KR'),
  ('grain-rice', '쌀', '쌀', 'canonical', 'ko-KR'),
  ('season-ssamjang', '쌈장', '쌈장', 'canonical', 'ko-KR'),
  ('misc-nuts', '아몬드', '아몬드', 'synonym', 'ko-KR'),
  ('fruit-avocado', '아보카도', '아보카도', 'canonical', 'ko-KR'),
  ('veg-young-napa', '알배기배추', '알배기배추', 'synonym', 'ko-KR'),
  ('veg-young-napa', '알배추', '알배추', 'canonical', 'ko-KR'),
  ('meat-pork', '앞다리살', '앞다리살', 'synonym', 'ko-KR'),
  ('veg-zucchini', '애호박', '애호박', 'canonical', 'ko-KR'),
  ('veg-cabbage', '양배추', '양배추', 'canonical', 'ko-KR'),
  ('veg-mushroom', '양송이버섯', '양송이버섯', 'synonym', 'ko-KR'),
  ('season-soy-dark', '양조간장', '양조간장', 'synonym', 'ko-KR'),
  ('veg-onion', '양파', '양파', 'canonical', 'ko-KR'),
  ('sea-fishcake', '어묵', '어묵', 'canonical', 'ko-KR'),
  ('season-mustard', '연겨자', '연겨자', 'synonym', 'ko-KR'),
  ('veg-lotus-root', '연근', '연근', 'canonical', 'ko-KR'),
  ('sea-salmon', '연어', '연어', 'canonical', 'ko-KR'),
  ('veg-garlic-chive', '영양부추', '영양부추', 'synonym', 'ko-KR'),
  ('fruit-orange', '오렌지', '오렌지', 'canonical', 'ko-KR'),
  ('misc-orange-juice', '오렌지주스', '오렌지주스', 'canonical', 'ko-KR'),
  ('meat-duck', '오리고기', '오리고기', 'canonical', 'ko-KR'),
  ('veg-cucumber', '오이', '오이', 'canonical', 'ko-KR'),
  ('sea-squid', '오징어', '오징어', 'canonical', 'ko-KR'),
  ('grain-oatmeal', '오트밀', '오트밀', 'canonical', 'ko-KR'),
  ('grain-starch', '옥수수전분', '옥수수전분', 'synonym', 'ko-KR'),
  ('proc-corn-can', '옥수수캔', '옥수수캔', 'canonical', 'ko-KR'),
  ('misc-syrup', '올리고당', '올리고당', 'canonical', 'ko-KR'),
  ('proc-olive', '올리브', '올리브', 'canonical', 'ko-KR'),
  ('dairy-yogurt', '요거트', '요거트', 'canonical', 'ko-KR'),
  ('season-cooking-wine', '요리술', '요리술', 'synonym', 'ko-KR'),
  ('grain-udon', '우동면', '우동면', 'canonical', 'ko-KR'),
  ('veg-burdock', '우엉', '우엉', 'canonical', 'ko-KR'),
  ('dairy-milk', '우유', '우유', 'canonical', 'ko-KR'),
  ('misc-coffee', '원두커피', '원두커피', 'synonym', 'ko-KR'),
  ('proc-stock', '육수팩', '육수팩', 'canonical', 'ko-KR'),
  ('grain-somen', '잔치국수면', '잔치국수면', 'synonym', 'ko-KR'),
  ('veg-chives', '잔파', '잔파', 'synonym', 'ko-KR'),
  ('proc-jam', '잼', '잼', 'canonical', 'ko-KR'),
  ('veg-onion', '적양파', '적양파', 'synonym', 'ko-KR'),
  ('grain-starch', '전분', '전분', 'canonical', 'ko-KR'),
  ('season-soy-soup', '조선간장', '조선간장', 'synonym', 'ko-KR'),
  ('veg-radish', '조선무', '조선무', 'synonym', 'ko-KR'),
  ('season-soy-dark', '진간장', '진간장', 'canonical', 'ko-KR'),
  ('veg-green-onion', '쪽파', '쪽파', 'synonym', 'ko-KR'),
  ('season-sesame-oil', '참기름', '참기름', 'canonical', 'ko-KR'),
  ('season-sesame-seed', '참깨', '참깨', 'synonym', 'ko-KR'),
  ('sea-tuna', '참치', '참치', 'canonical', 'ko-KR'),
  ('proc-tuna-can', '참치캔', '참치캔', 'canonical', 'ko-KR'),
  ('proc-tuna-can', '참치 통조림', '참치통조림', 'synonym', 'ko-KR'),
  ('veg-bok-choy', '청경채', '청경채', 'canonical', 'ko-KR'),
  ('veg-chili-pepper', '청양고추', '청양고추', 'synonym', 'ko-KR'),
  ('veg-tomato-cherry', '체리토마토', '체리토마토', 'synonym', 'ko-KR'),
  ('dairy-cheese', '치즈', '치즈', 'canonical', 'ko-KR'),
  ('season-chicken-stock', '치킨스톡', '치킨스톡', 'canonical', 'ko-KR'),
  ('season-curry', '카레가루', '카레가루', 'canonical', 'ko-KR'),
  ('misc-coffee', '커피', '커피', 'canonical', 'ko-KR'),
  ('season-ketchup', '케첩', '케첩', 'canonical', 'ko-KR'),
  ('misc-cocoa', '코코아가루', '코코아가루', 'canonical', 'ko-KR'),
  ('veg-bean-sprout', '콩나물', '콩나물', 'canonical', 'ko-KR'),
  ('proc-beans-can', '콩통조림', '콩통조림', 'canonical', 'ko-KR'),
  ('dairy-cream-cheese', '크림치즈', '크림치즈', 'canonical', 'ko-KR'),
  ('fruit-kiwi', '키위', '키위', 'canonical', 'ko-KR'),
  ('misc-sparkling-water', '탄산수', '탄산수', 'canonical', 'ko-KR'),
  ('proc-sauce-pasta', '토마토소스', '토마토소스', 'canonical', 'ko-KR'),
  ('proc-tomato-can', '토마토캔', '토마토캔', 'canonical', 'ko-KR'),
  ('season-ketchup', '토마토케첩', '토마토케첩', 'synonym', 'ko-KR'),
  ('season-sesame-seed', '통깨', '통깨', 'synonym', 'ko-KR'),
  ('veg-garlic', '통마늘', '통마늘', 'synonym', 'ko-KR'),
  ('misc-tea', '티백', '티백', 'canonical', 'ko-KR'),
  ('veg-green-onion', '파', '파', 'synonym', 'ko-KR'),
  ('dairy-parmesan', '파마산', '파마산', 'synonym', 'ko-KR'),
  ('dairy-parmesan', '파마산치즈', '파마산치즈', 'canonical', 'ko-KR'),
  ('grain-pasta', '파스타면', '파스타면', 'canonical', 'ko-KR'),
  ('proc-sauce-pasta', '파스타소스', '파스타소스', 'synonym', 'ko-KR'),
  ('fruit-pineapple', '파인애플', '파인애플', 'canonical', 'ko-KR'),
  ('veg-paprika', '파프리카', '파프리카', 'canonical', 'ko-KR'),
  ('fruit-grape', '포도', '포도', 'canonical', 'ko-KR'),
  ('veg-mushroom', '표고버섯', '표고버섯', 'synonym', 'ko-KR'),
  ('veg-chili-pepper', '풋고추', '풋고추', 'synonym', 'ko-KR'),
  ('dairy-yogurt', '플레인요거트', '플레인요거트', 'synonym', 'ko-KR'),
  ('proc-pickle', '피클', '피클', 'canonical', 'ko-KR'),
  ('meat-ham', '햄', '햄', 'canonical', 'ko-KR'),
  ('proc-spam', '햄통조림', '햄통조림', 'synonym', 'ko-KR'),
  ('grain-brown-rice', '현미', '현미', 'canonical', 'ko-KR'),
  ('misc-nuts', '호두', '호두', 'synonym', 'ko-KR'),
  ('veg-sweet-potato', '호박고구마', '호박고구마', 'synonym', 'ko-KR'),
  ('proc-tomato-can', '홀토마토', '홀토마토', 'synonym', 'ko-KR'),
  ('veg-chili-pepper', '홍고추', '홍고추', 'synonym', 'ko-KR'),
  ('misc-tea', '홍차', '홍차', 'synonym', 'ko-KR'),
  ('sea-dried-pollack', '황태채', '황태채', 'canonical', 'ko-KR'),
  ('season-pepper', '후추', '후추', 'canonical', 'ko-KR'),
  ('season-pepper', '후춧가루', '후춧가루', 'synonym', 'ko-KR'),
  ('dairy-whipping-cream', '휘핑크림', '휘핑크림', 'synonym', 'ko-KR'),
  ('veg-onion', '흰양파', '흰양파', 'synonym', 'ko-KR')
on conflict (locale, normalized_alias) do update
set ingredient_id = excluded.ingredient_id,
    alias = excluded.alias,
    alias_type = excluded.alias_type;

notify pgrst, 'reload schema';
